/*
 * Copyright (c) 2026 Ivan Tugay
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Generated by cbindgen from crates/scull-ffi/src:
 * `just bindings`. Do not edit.
 */

#ifndef SCULL_H
#define SCULL_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Breaking changes bump the major version; a host refuses to run on
// another major.
#define TT_ABI_VERSION_MAJOR 0

// Additions (new functions, fields appended to a struct) bump the minor.
// While the major is 0 every minor may break, so the minor must match too.
#define TT_ABI_VERSION_MINOR 6

// The version a host was built against, `major << 16 | minor`; pass it
// in `tt_term_options.abi_version`.
#define TT_ABI_VERSION 6

// `tt_keybind.action`: paste the clipboard.
#define TT_ACTION_PASTE 1

// Make the font one point larger.
#define TT_ACTION_FONT_LARGER 2

// Make the font one point smaller.
#define TT_ACTION_FONT_SMALLER 3

// Back to the configured font size.
#define TT_ACTION_FONT_RESET 4

// Scroll the history one screen up.
#define TT_ACTION_SCROLL_PAGE_UP 5

// Scroll the history one screen down.
#define TT_ACTION_SCROLL_PAGE_DOWN 6

// Scroll to the oldest history row.
#define TT_ACTION_SCROLL_TO_TOP 7

// Scroll back to the screen.
#define TT_ACTION_SCROLL_TO_BOTTOM 8

// `tt_event.kind`: the program rang the bell, once or more since the last
// poll.
#define TT_EVENT_BELL 1

// `tt_event.kind`: the child ended and all its output has been parsed.
// Reported once, last.
#define TT_EVENT_CHILD_EXITED 2

// `tt_event.kind`: OSC 0, 1 or 2 named the window or icon. `detail` is a
// `TT_TITLE_*`; the text is the name.
#define TT_EVENT_TITLE 3

// `tt_event.kind`: OSC 7 reported the working directory; the text is its
// `file://` URI as the program sent it.
#define TT_EVENT_WORKING_DIRECTORY 4

// `tt_event.kind`: an OSC 133 shell mark. `detail` is the marker letter
// (`A` prompt, `B` command, `C` output, `D` done); the text is what
// followed it, often an exit code.
#define TT_EVENT_SHELL_MARK 5

// `tt_event.kind`: OSC 52 asks for the clipboard. `id` is the request:
// answer it with `tt_term_clipboard_reply` or `tt_term_clipboard_deny`.
// `detail` is the selection byte (`c`, `p`, `q`, `s`, `0`-`7`).
#define TT_EVENT_CLIPBOARD_READ 6

// `tt_event.kind`: OSC 52 sets the clipboard; the text is the decoded
// bytes, which need not be UTF-8. `detail` is the selection byte.
#define TT_EVENT_CLIPBOARD_WRITE 7

// `tt_event.kind`: OSC 8 opened a hyperlink. `id` is its link id; the text
// is the URI. `tt_term_link_uri` resolves the id later.
#define TT_EVENT_LINK 8

// `tt_event.kind`: OSC 9 or OSC 777 `notify` asks for a notification. The
// text is the message, `TT_EVENT_TEXT_TITLE` its title (empty for OSC 9).
#define TT_EVENT_NOTIFICATION 9

// `tt_event.detail` of `TT_EVENT_TITLE`: OSC 0, icon name and window title.
#define TT_TITLE_BOTH 0

// `tt_event.detail` of `TT_EVENT_TITLE`: OSC 1, the icon name.
#define TT_TITLE_ICON 1

// `tt_event.detail` of `TT_EVENT_TITLE`: OSC 2, the window title.
#define TT_TITLE_WINDOW 2

// `tt_term_event_text` part: the event's text, `text_len` bytes.
#define TT_EVENT_TEXT_BODY 0

// `tt_term_event_text` part: a notification's title, `title_len` bytes.
#define TT_EVENT_TEXT_TITLE 1

// `tt_event.exit_code` when the system did not say. A literal, not the
// PTY crate's constant, so the generated header can spell it.
#define TT_EXIT_CODE_UNKNOWN 4294967295

// The cell holds more code points than `codepoint`; the whole cluster is
// in its row's text.
#define TT_CELL_CLUSTER 1

// A colour: `TT_COLOR_DEFAULT`, `TT_COLOR_INDEXED | index` or
// `TT_COLOR_RGB | 0xRRGGBB`; the kind is in `TT_COLOR_KIND_MASK`.
#define TT_COLOR_DEFAULT 0

// Palette colour, index in the low byte.
#define TT_COLOR_INDEXED 16777216

// True colour in the low three bytes.
#define TT_COLOR_RGB 33554432

// The bits that hold a colour's kind.
#define TT_COLOR_KIND_MASK 4278190080

// `tt_style.attrs` bits.
#define TT_ATTR_BOLD 1

// Faint.
#define TT_ATTR_DIM 2

// Italic.
#define TT_ATTR_ITALIC 4

// Blinking.
#define TT_ATTR_BLINK 8

// Foreground and background swapped.
#define TT_ATTR_INVERSE 16

// Invisible text.
#define TT_ATTR_HIDDEN 32

// Struck through.
#define TT_ATTR_STRIKE 64

// Line above.
#define TT_ATTR_OVERLINE 128

// `tt_style.underline` values.
#define TT_UNDERLINE_NONE 0

// One line.
#define TT_UNDERLINE_SINGLE 1

// Two lines.
#define TT_UNDERLINE_DOUBLE 2

// Wavy.
#define TT_UNDERLINE_CURLY 3

// Dotted.
#define TT_UNDERLINE_DOTTED 4

// Dashed.
#define TT_UNDERLINE_DASHED 5

// Most bytes of composing text a frame shows.
#define TT_MAX_PREEDIT_BYTES 1024

// `tt_key_event.action`: the key went down.
#define TT_KEY_PRESS 1

// The key auto-repeats.
#define TT_KEY_REPEAT 2

// The key went up.
#define TT_KEY_RELEASE 3

// `tt_key_event.mods` and `tt_mouse_event.mods` bits.
#define TT_MOD_SHIFT 1

// Alt, Option on macOS.
#define TT_MOD_ALT 2

// Control.
#define TT_MOD_CTRL 4

// Super: Command on macOS, the Windows key.
#define TT_MOD_SUPER 8

// Hyper.
#define TT_MOD_HYPER 16

// Meta.
#define TT_MOD_META 32

// Caps Lock is on.
#define TT_MOD_CAPS_LOCK 64

// Num Lock is on.
#define TT_MOD_NUM_LOCK 128

// `tt_key_event.key`: Escape. The keys after it, one code each, are
// Enter, Tab, Backspace, Insert, Delete, Left, Right, Up, Down, Page Up,
// Page Down, Home and End (`TT_KEY_END`).
#define TT_KEY_ESCAPE 57344

// The last of the keys from `TT_KEY_ESCAPE`.
#define TT_KEY_END 57357

// Caps Lock; then Scroll Lock, Num Lock, Print Screen, Pause, Menu.
#define TT_KEY_CAPS_LOCK 57358

// F1; F`n` is `TT_KEY_F1 + n - 1` up to F35.
#define TT_KEY_F1 57364

// Keypad 0; then 1 to 9, Decimal, Divide, Multiply, Subtract, Add, Enter,
// Equal, Separator, Left, Right, Up, Down, Page Up, Page Down, Home, End,
// Insert, Delete, Begin.
#define TT_KEY_KP_0 57399

// Play; then Pause, Play/Pause, Reverse, Stop, Fast Forward, Rewind, Next
// Track, Previous Track, Record, Volume Down, Volume Up, Mute.
#define TT_KEY_MEDIA_PLAY 57428

// Left Shift on its own; then Left Control, Left Alt, Left Super, Left
// Hyper, Left Meta, the same six on the right, ISO Level 3 Shift and ISO
// Level 5 Shift.
#define TT_KEY_LEFT_SHIFT 57441

// `tt_mouse_event.action`: a button went down; wheel steps are presses.
#define TT_MOUSE_PRESS 1

// A button went up.
#define TT_MOUSE_RELEASE 2

// The pointer moved to another cell, or pixel while the program asks
// for pixels; send it only then.
#define TT_MOUSE_MOTION 3

// `tt_mouse_event.button`: none, for motion with no button held. Others
// are X11's numbers: 1 left, 2 middle, 3 right, 4 to 7 wheel up, down,
// left and right, 8 back, 9 forward, 10 and 11.
#define TT_MOUSE_NONE 0

// The left button.
#define TT_MOUSE_LEFT 1

// The middle button.
#define TT_MOUSE_MIDDLE 2

// The right button.
#define TT_MOUSE_RIGHT 3

// One wheel step up.
#define TT_MOUSE_WHEEL_UP 4

// One wheel step down.
#define TT_MOUSE_WHEEL_DOWN 5

// One wheel step left.
#define TT_MOUSE_WHEEL_LEFT 6

// One wheel step right.
#define TT_MOUSE_WHEEL_RIGHT 7

// What every fallible call answers. Values are only ever appended.
enum tt_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Done.
  TT_OK = 0,
  // A `NULL` handle or pointer, a `struct_size` too small, a size of
  // zero, or text that is not UTF-8.
  TT_INVALID = 1,
  // The host was built against another ABI version.
  TT_ABI_MISMATCH = 2,
  // An earlier call panicked inside this terminal; only
  // `tt_term_free` is left to call.
  TT_POISONED = 3,
  // This call panicked inside the core; the terminal is now poisoned.
  TT_PANIC = 4,
  // Nothing to report: the event queue is empty, or the event text or
  // link asked for is no longer held.
  TT_EMPTY = 5,
  // The terminal has no child to talk to: it was made by
  // `tt_term_new`, or its child has gone.
  TT_CLOSED = 6,
  // The operating system refused: no PTY, a program that does not
  // start, a size the PTY rejects.
  TT_IO = 7,
  // The child is not reading and its input queue cannot take the whole
  // event; nothing was sent. Try again later.
  TT_FULL = 8,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum tt_status tt_status;
#else
typedef int32_t tt_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// The configuration. Opaque to the host.
typedef struct tt_config tt_config;

// A UI-owned frame. Opaque to the host; one per view, used from one
// thread at a time.
typedef struct tt_frame tt_frame;

// An image's pixels, shared and immutable. Opaque to the host: read it
// with `tt_image_pixels`.
typedef struct tt_image tt_image;

// One terminal. Opaque to the host.
typedef struct tt_term tt_term;

// UTF-8 text the host owns: `len` bytes at `ptr`, no terminator. `ptr`
// may be `NULL` when `len` is 0.
typedef struct tt_str {
  // The first byte.
  const uint8_t *ptr;
  // Bytes, not characters.
  size_t len;
} tt_str;

// Called with the `userdata` given at spawn when the terminal has
// something new: output to draw or an event to poll. It runs on a core
// thread and must not block, unwind or call any `tt_*` function: post a
// redraw to the UI thread and return. It is not called again until the
// host calls `tt_frame_update` or `tt_term_poll_event` on the terminal,
// and never after `tt_term_free` returns.
typedef void (*tt_wakeup_fn)(void *userdata);

// How to open the configuration.
typedef struct tt_config_options {
  // `sizeof(tt_config_options)` as the host knows it.
  uint32_t struct_size;
  // `TT_ABI_VERSION` as the host was built with it.
  uint32_t abi_version;
  // The config file; empty for the default place
  // (`$XDG_CONFIG_HOME/scull/config.toml`, `~/.config/scull/config.toml`,
  // `%APPDATA%\scull\config.toml`).
  struct tt_str path;
  // Called from a core thread when `tt_config_poll` would answer
  // something new; `NULL` for none. Same contract as `tt_wakeup_fn`:
  // it must not block or call `tt_*`, it is not called again until the
  // host polls, and never after `tt_config_free` returns.
  tt_wakeup_fn wakeup;
  // Passed to `wakeup` as is.
  void *userdata;
} tt_config_options;

// A key binding: when `key` is pressed with exactly `mods` among Shift,
// Alt, Control and Super held, do `action`.
typedef struct tt_keybind {
  // As `tt_key_event.key`.
  uint32_t key;
  // `TT_MOD_*` bits.
  uint8_t mods;
  // `TT_ACTION_*`.
  uint8_t action;
} tt_keybind;

// The settings in force. Every pointer in it stays valid until the next
// `tt_config_poll` or `tt_config_free` on the same handle.
typedef struct tt_config_view {
  // `sizeof(tt_config_view)` as the host knows it.
  uint32_t struct_size;
  // 1 when anything changed since the previous poll (always on the first).
  uint8_t updated;
  // 1 when file changes are watched; 0 means only `tt_config_set` and a
  // new handle see the file.
  uint8_t watching;
  // Grows with every change of the settings or of `error`.
  uint64_t generation;
  // The font family; empty for the platform's monospace font.
  struct tt_str font_family;
  // The font size in points.
  float font_size;
  // History rows for terminals opened from now on.
  uint32_t scrollback;
  // The colour scheme's name as the file spells it (`scull-dark`, ...).
  struct tt_str scheme;
  // Default text colour, `0xRRGGBB`.
  uint32_t foreground;
  // Default background colour, `0xRRGGBB`.
  uint32_t background;
  // Cursor colour, `0xRRGGBB`.
  uint32_t cursor;
  // Palette entries 0 to 15, `0xRRGGBB`.
  uint32_t ansi[16];
  // The key bindings in force.
  const struct tt_keybind *keybinds;
  // Number of `keybinds`.
  size_t keybinds_len;
  // Why the file could not be used the last time it was read, with its
  // name; empty when it was fine. The settings above are then the last
  // good ones.
  struct tt_str error;
  // The config file's path.
  struct tt_str path;
} tt_config_view;

// One event. A `u32` kind rather than an enum, so a kind added later is a
// value an older host skips, not undefined behaviour.
typedef struct tt_event {
  // `sizeof(tt_event)` as the host knows it.
  uint32_t struct_size;
  // One of `TT_EVENT_*`; skip kinds you do not know.
  uint32_t kind;
  // `TT_EVENT_CHILD_EXITED`: the exit code, or `TT_EXIT_CODE_UNKNOWN`.
  uint32_t exit_code;
  // `TT_EVENT_CHILD_EXITED`: 1 when a signal ended the child.
  uint8_t signaled;
  // Names this event to `tt_term_event_text`; never 0.
  uint64_t serial;
  // The clipboard request of `TT_EVENT_CLIPBOARD_*`, the link id of
  // `TT_EVENT_LINK`; 0 otherwise.
  uint64_t id;
  // Per kind: a `TT_TITLE_*`, a shell marker letter, a clipboard
  // selection byte; 0 otherwise.
  uint32_t detail;
  // Bytes of the text (`TT_EVENT_TEXT_BODY`); 0 when there is none.
  uint32_t text_len;
  // Bytes of a notification's title (`TT_EVENT_TEXT_TITLE`).
  uint32_t title_len;
} tt_event;

// The cursor in viewport rows.
typedef struct tt_cursor {
  // Viewport row.
  uint16_t row;
  // Column.
  uint16_t col;
  // 0 when hidden or scrolled out of the viewport.
  uint8_t visible;
} tt_cursor;

// One cell: 8 bytes, row after row, `cols * rows` of them.
typedef struct tt_cell {
  // The first code point of the cell's text; 0 when it shows none.
  uint32_t codepoint;
  // Index into `tt_frame_view.styles`.
  uint16_t style;
  // Columns covered: 1, 2 for a wide character, 0 for the cell behind it.
  uint8_t width;
  // `TT_CELL_CLUSTER` or 0.
  uint8_t flags;
} tt_cell;

// Neighbouring cells of one style and width with their text, the unit the
// platform shaper takes. Blank cells belong to no run.
typedef struct tt_run {
  // First column.
  uint16_t col;
  // Columns covered, wide spacers included.
  uint16_t cols;
  // Index into `tt_frame_view.styles`.
  uint16_t style;
  // Columns per character: 1 or 2.
  uint8_t width;
  // Byte offset of the run's text in its row's `text`.
  uint32_t text_start;
  // Byte length of the run's text.
  uint32_t text_len;
} tt_run;

// One viewport row: the line it shows and its text.
typedef struct tt_row {
  // The line shown; stays with the line as it scrolls, so it keys a
  // cache of shaped rows.
  uint64_t id;
  // Bumped by every change to the line.
  uint32_t generation;
  // The row's text runs, left to right.
  const struct tt_run *runs;
  // Number of runs.
  size_t runs_len;
  // UTF-8 text of all runs, not NUL-terminated.
  const uint8_t *text;
  // Bytes of text.
  size_t text_len;
} tt_row;

// A style as SGR set it; palette and reverse video are not resolved yet.
typedef struct tt_style {
  // Foreground colour.
  uint32_t fg;
  // Background colour.
  uint32_t bg;
  // Underline colour; `TT_COLOR_DEFAULT` follows the foreground.
  uint32_t underline_color;
  // `TT_ATTR_*` bits.
  uint16_t attrs;
  // A `TT_UNDERLINE_*` value.
  uint8_t underline;
} tt_style;

// Rows `start..end` are, unchanged, the rows from `from` of the previous
// picture: blit them before repainting the dirty rows.
typedef struct tt_scroll {
  // First row moved into.
  uint16_t start;
  // One past the last row moved into.
  uint16_t end;
  // Where `start` was in the previous picture.
  uint16_t from;
} tt_scroll;

// One image in the viewport. Draw the source rectangle of `image` scaled
// to `cols` x `rows` cells whose top-left cell is (`row`, `col`), moved by
// the pixel offset. Placements come lowest `z` first; a negative `z`
// draws below the text.
typedef struct tt_placement {
  // The pixels; valid until the next update or free of the frame, or
  // until `tt_image_release` after a `tt_image_retain`.
  const struct tt_image *image;
  // Changes whenever the pixels behind `image` may have; a texture cache
  // keys on `image` and `generation`.
  uint64_t generation;
  // Viewport row of the top-left cell; negative above the viewport.
  int32_t row;
  // Column of the top-left cell.
  uint32_t col;
  // Width in cells.
  uint32_t cols;
  // Height in cells.
  uint32_t rows;
  // Pixel offset inside the top-left cell.
  uint32_t offset_x;
  // Pixel offset inside the top-left cell.
  uint32_t offset_y;
  // Source rectangle in image pixels: left edge.
  uint32_t src_x;
  // Top edge.
  uint32_t src_y;
  // Width.
  uint32_t src_w;
  // Height.
  uint32_t src_h;
  // Stacking order.
  int32_t z;
} tt_placement;

// Where the frame shows the input method's composing text, set with
// `tt_frame_preedit`. The text is already in the row's cells and runs and
// the cursor is at its caret; a renderer only marks the span, usually
// with an underline. `cols` is 0 when none is shown.
typedef struct tt_preedit {
  // Viewport row.
  uint16_t row;
  // First column.
  uint16_t col;
  // Columns covered.
  uint16_t cols;
} tt_preedit;

// What `tt_frame_update` hands back. Set `struct_size` before the call.
typedef struct tt_frame_view {
  // `sizeof(tt_frame_view)` as the host knows it; on return, the bytes
  // the core filled in.
  uint32_t struct_size;
  // Columns.
  uint16_t cols;
  // Rows.
  uint16_t rows;
  // 0 while synchronized output (mode 2026) holds the picture: nothing
  // changed and there is no damage; keep showing the last frame.
  uint8_t updated;
  // 1 when every row must be repainted (first frame, resize, other
  // screen); every row is then also listed in `dirty`.
  uint8_t full;
  // The cursor.
  struct tt_cursor cursor;
  // `cols * rows` cells, row-major.
  const struct tt_cell *cells;
  // Number of cells.
  size_t cells_len;
  // One entry per viewport row.
  const struct tt_row *lines;
  // Number of rows in `lines`.
  size_t lines_len;
  // The style table that cells and runs index; entry 0 is the default.
  const struct tt_style *styles;
  // Number of styles.
  size_t styles_len;
  // Rows to blit from the previous picture, applied before `dirty`.
  const struct tt_scroll *scrolls;
  // Number of scrolls.
  size_t scrolls_len;
  // Rows to repaint, top to bottom.
  const uint16_t *dirty;
  // Number of dirty rows.
  size_t dirty_len;
  // The images in the viewport, lowest `z` first. The rows they cover
  // are in `dirty` whenever a placement over them changed.
  const struct tt_placement *placements;
  // Number of placements.
  size_t placements_len;
  // The composing text's span; its row is in `dirty` whenever it
  // changed.
  struct tt_preedit preedit;
} tt_frame_view;

// One key event, as Ghostty's embedding API reports it: what was
// pressed and what text it typed; the core picks the bytes.
typedef struct tt_key_event {
  // `sizeof(tt_key_event)` as the host knows it.
  uint32_t struct_size;
  // The key: for a key of the main block, the code point it types on
  // the US layout with no modifiers (`'a'`, `'1'`, `' '`); for any
  // other key a `TT_KEY_*` code.
  uint32_t key;
  // What the key types on the current layout with no modifiers (`с`
  // for the `c` key on a Russian layout); 0 when it is `key` itself.
  uint32_t unshifted;
  // `TT_KEY_PRESS`, `TT_KEY_REPEAT` or `TT_KEY_RELEASE`.
  uint8_t action;
  // `TT_MOD_*` bits held, including this key if it is a modifier.
  uint8_t mods;
  // `TT_MOD_*` bits the layout used to type `text` (Option typing `å`).
  uint8_t consumed_mods;
  // 1 while an input method is composing: nothing is sent.
  uint8_t composing;
  // UTF-8 the key typed, with Shift and consumed modifiers but not
  // Control applied; may be empty.
  struct tt_str text;
} tt_key_event;

// One mouse event, in cells and in pixels: the core picks which the
// program gets.
typedef struct tt_mouse_event {
  // `sizeof(tt_mouse_event)` as the host knows it.
  uint32_t struct_size;
  // `TT_MOUSE_PRESS`, `TT_MOUSE_RELEASE` or `TT_MOUSE_MOTION`.
  uint8_t action;
  // The button pressed or released; for motion, the lowest one held or
  // `TT_MOUSE_NONE`.
  uint8_t button;
  // `TT_MOD_*` bits; Shift, Alt and Control are reported.
  uint8_t mods;
  // Viewport column, from 0.
  uint32_t col;
  // Viewport row, from 0.
  uint32_t row;
  // Pixels from the left of the text area.
  uint32_t x_px;
  // Pixels from the top of the text area.
  uint32_t y_px;
} tt_mouse_event;

// How to create a terminal. Fields a host does not know read as zero;
// `tt_term_new` reads only up to `scrollback`.
typedef struct tt_term_options {
  // `sizeof(tt_term_options)` as the host knows it.
  uint32_t struct_size;
  // `TT_ABI_VERSION` as the host was built with it.
  uint32_t abi_version;
  // Columns, at least 1.
  uint16_t cols;
  // Rows, at least 1.
  uint16_t rows;
  // History rows to keep; the core clamps it.
  uint32_t scrollback;
  // The program, searched on `PATH`; empty runs the user's shell.
  struct tt_str program;
  // `args_len` arguments; ignored for the user's shell.
  const struct tt_str *args;
  // Number of `args`.
  size_t args_len;
  // Working directory; empty keeps the host's.
  struct tt_str cwd;
  // `env_len` `NAME=value` entries added to the host's environment.
  const struct tt_str *env;
  // Number of `env`.
  size_t env_len;
  // Called from a core thread when there is something new to draw or
  // poll; `NULL` for none. See `tt_wakeup_fn`.
  tt_wakeup_fn wakeup;
  // Passed to `wakeup` as is.
  void *userdata;
} tt_term_options;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The ABI version of this library, `major << 16 | minor`.
uint32_t tt_abi_version(void);

// Opens the configuration and starts watching it. A missing file is the
// defaults and a broken one is an `error` in the view, so this fails only
// for bad arguments or a host with no home directory to put the file in.
// On `TT_OK` `*out` holds the handle; free it with `tt_config_free`.
//
// # Safety
//
// `options` is `NULL` or points to `struct_size` readable bytes, its
// strings valid for their lengths during this call; `out` is `NULL` or
// writable.
tt_status tt_config_new(const struct tt_config_options *options, struct tt_config **out);

// Fills `*view` with the settings in force and sets `updated` when they
// are not what the previous poll returned. Polling lets the next wakeup
// fire.
//
// # Safety
//
// `config` is `NULL` or live; `view` is `NULL` or points to `struct_size`
// writable bytes.
tt_status tt_config_poll(const struct tt_config *config, struct tt_config_view *view);

// Changes one setting in the config file, keeping the rest of the file as
// it is, and applies it at once. `key` is one of `font.family`,
// `font.size`, `colors.scheme`, `colors.foreground`, `colors.background`,
// `colors.cursor`, `scrollback`; `value` is its text (`13.5`,
// `solarized-dark`, `#1a2b3c`), and an empty `value` removes the key so its
// default applies. `TT_INVALID` for an unknown key or a value the config
// does not accept, with the file untouched; `TT_IO` when it cannot be
// written.
//
// # Safety
//
// `config` is `NULL` or live; the strings are valid for their lengths.
tt_status tt_config_set(const struct tt_config *config, struct tt_str key, struct tt_str value);

// Frees the configuration and stops its watcher. `NULL` is a no-op. No
// other call may use `config` during or after this one.
//
// # Safety
//
// `config` is `NULL` or live, and not used again.
void tt_config_free(struct tt_config *config);

// Takes the next event into `*event`: `TT_OK` with one, `TT_EMPTY` when
// there is none. Call it until `TT_EMPTY` after every wakeup. The event's
// text stays readable through `tt_term_event_text` until the next poll.
//
// # Safety
//
// `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
// writable bytes.
tt_status tt_term_poll_event(const struct tt_term *term, struct tt_event *event);

// Copies part `part` (`TT_EVENT_TEXT_*`) of the text of event `serial`
// into `buf`, as `tt_term_read_text` does: `*len` becomes its length, and
// `TT_FULL` with nothing copied when that is more than `cap`. Only the
// event polled last is held: an older `serial` answers `TT_EMPTY`.
// `TT_INVALID` for an unknown part, a `NULL` `len`, or a `NULL` `buf` with
// a `cap`.
//
// # Safety
//
// `term` is `NULL` or live; `buf` is `NULL` or points to `cap` writable
// bytes; `len` is `NULL` or writable.
tt_status tt_term_event_text(const struct tt_term *term,
                             uint64_t serial,
                             uint32_t part,
                             uint8_t *buf,
                             size_t cap,
                             size_t *len);

// Copies the URI of link `id` (from `TT_EVENT_LINK`) into `buf`, sized
// as for `tt_term_event_text`. An id stays valid while text on the screen
// or in history carries it; `TT_EMPTY` once it is gone, after which the
// core may hand the id to a new link.
//
// # Safety
//
// As for `tt_term_event_text`.
tt_status tt_term_link_uri(const struct tt_term *term,
                           uint32_t id,
                           uint8_t *buf,
                           size_t cap,
                           size_t *len);

// Answers the OSC 52 read `id` with `len` bytes of clipboard content,
// which the core base64-encodes for the program. `TT_INVALID` when `id`
// is not an open read (unknown, or answered already), when the content is
// over 1 MiB, or for `NULL` `data` with a `len`; `TT_FULL` when the reply
// did not fit and the program got an empty answer instead.
//
// # Safety
//
// `term` is `NULL` or live; `data` points to `len` readable bytes.
tt_status tt_term_clipboard_reply(const struct tt_term *term,
                                  uint64_t id,
                                  const uint8_t *data,
                                  size_t len);

// Refuses the OSC 52 read `id`: the program gets an empty answer, so it
// does not wait. `TT_INVALID` when `id` is not an open read.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_clipboard_deny(const struct tt_term *term, uint64_t id);

// A new, empty frame; the first update fills it. `NULL` only if the core
// failed. Free it with `tt_frame_free`.
struct tt_frame *tt_frame_new(void);

// Brings `frame` up to date with `term`'s viewport and describes it in
// `*view`. Holds the terminal lock only while it copies the rows that
// changed. The pointers in `*view` stay valid until the next update or
// free of this frame.
//
// # Safety
//
// `frame` and `term` are `NULL` or live; `view` is `NULL` or points to
// `struct_size` writable bytes. No other thread uses `frame` meanwhile.
tt_status tt_frame_update(struct tt_frame *frame,
                          const struct tt_term *term,
                          struct tt_frame_view *view);

// Sets the input method's composing text, UTF-8, with the caret at byte
// `caret` (moved back onto a character boundary); `len` 0 clears it. The
// next `tt_frame_update` shows it at the cursor (`tt_frame_view.preedit`).
// It never reaches the child: commit text with `tt_term_text`. Text past
// `TT_MAX_PREEDIT_BYTES` is cut. `TT_INVALID` for a `NULL` frame or text
// that is not UTF-8.
//
// # Safety
//
// `frame` is `NULL` or live and not used by another thread meanwhile;
// `bytes` points to `len` readable bytes.
tt_status tt_frame_preedit(struct tt_frame *frame, const uint8_t *bytes, size_t len, size_t caret);

// Frees the frame and every buffer its views pointed to. `NULL` is a
// no-op.
//
// # Safety
//
// `frame` is `NULL` or live, and not used again.
void tt_frame_free(struct tt_frame *frame);

// Takes a reference to `image`, so its pixels outlive the frame update
// that handed it out. `NULL` is a no-op.
//
// # Safety
//
// `image` is `NULL`, a `tt_placement.image` whose view is still valid, or
// an image retained and not yet released. Any thread may call this.
void tt_image_retain(const struct tt_image *image);

// Drops a reference taken by `tt_image_retain`. `NULL` is a no-op.
//
// # Safety
//
// `image` is `NULL` or was retained, and each retain is released once.
void tt_image_release(const struct tt_image *image);

// The pixels of `image`: `height` rows of `stride` bytes, each `width`
// RGBA pixels of 4 bytes, straight (not premultiplied) alpha. Valid while
// `image` is. Each out pointer may be `NULL`; a `NULL` image answers
// `NULL` and zeroes them.
//
// # Safety
//
// `image` is as for `tt_image_retain`; each out pointer is `NULL` or
// writable.
const uint8_t *tt_image_pixels(const struct tt_image *image,
                               uint32_t *width,
                               uint32_t *height,
                               size_t *stride);

// Sends a key event. `TT_OK` also when the active modes send nothing
// for it (a release in legacy mode, a composing key); `TT_CLOSED` when
// there is no child; `TT_FULL` when the child is not reading and its
// input queue lacks room, in which case nothing was sent.
//
// # Safety
//
// `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
// readable bytes whose `text` is valid for its length.
tt_status tt_term_key(const struct tt_term *term, const struct tt_key_event *event);

// Sends text an input method committed outside a key event (dictation,
// the character viewer). Control characters are dropped. Statuses as for
// `tt_term_key`; `TT_INVALID` for text that is not UTF-8.
//
// # Safety
//
// `term` is `NULL` or live; `bytes` points to `len` readable bytes.
tt_status tt_term_text(const struct tt_term *term, const uint8_t *bytes, size_t len);

// Sends pasted text: bracketed, with any bracket marker inside removed,
// while the program asks for it (mode 2004); otherwise line feeds become
// carriage returns. A paste is sent whole or not at all, so one larger
// than the child's input queue (256 KiB) answers `TT_FULL`. Statuses
// otherwise as for `tt_term_text`.
//
// # Safety
//
// `term` is `NULL` or live; `bytes` points to `len` readable bytes.
tt_status tt_term_paste(const struct tt_term *term, const uint8_t *bytes, size_t len);

// Tells the program the view gained (`focused` 1) or lost (0) focus,
// while it asks for focus reports (mode 1004). Statuses as for
// `tt_term_key`.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_focus(const struct tt_term *term, uint8_t focused);

// Sends a mouse event if the program takes it. `*taken`, unless `NULL`,
// becomes 1 when it does: always while it tracks the mouse, and for a
// wheel step on the alternate screen, which becomes a cursor key (mode
// 1007). At 0 the event is the host's: select, or scroll the history
// with `tt_term_scroll_display`. Statuses as for `tt_term_key`.
//
// # Safety
//
// `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
// readable bytes; `taken` is `NULL` or writable.
tt_status tt_term_mouse(const struct tt_term *term,
                        const struct tt_mouse_event *event,
                        uint8_t *taken);

// Moves the viewport `delta` rows back into history (negative: towards
// the screen), clamped to what history holds. Typing, text and paste
// bring it back to the screen by themselves.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_scroll_display(const struct tt_term *term, int32_t delta);

// Creates a terminal running a child on a new PTY: `options.program`
// with its arguments, or the user's shell. Output is parsed on core
// threads; `options.wakeup` says when to look. On `TT_OK` `*out` holds
// the handle; free it with `tt_term_free`, which ends the child.
//
// # Safety
//
// As for `tt_term_new`; the strings and arrays in `*options` are valid
// for their lengths, during this call only.
tt_status tt_term_spawn(const struct tt_term_options *options, struct tt_term **out);

// Queues `len` bytes of input (keys, paste) for the child without
// blocking. `*written` gets how many leading bytes were taken: fewer than
// `len` when the child is not reading; offer the rest later. `TT_CLOSED`
// when there is no child or it has gone.
//
// # Safety
//
// `term` is `NULL` or live; `bytes` points to `len` readable bytes;
// `written` is `NULL` or writable.
tt_status tt_term_write(const struct tt_term *term,
                        const uint8_t *bytes,
                        size_t len,
                        size_t *written);

// Starts an interactive resize: the child's output is held back, so the
// host keeps drawing the last frame, until `tt_term_resize` with the final
// size. Without it every intermediate size would rewrap the history.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_resize_begin(const struct tt_term *term);

// Creates a terminal with no child process: bytes reach it only through
// `tt_term_feed`. On `TT_OK` `*out` holds the handle; free it with
// `tt_term_free`.
//
// # Safety
//
// `options` is `NULL` or points to `struct_size` readable bytes; `out` is
// `NULL` or writable.
tt_status tt_term_new(const struct tt_term_options *options, struct tt_term **out);

// Parses `len` bytes of program output into the terminal, as if the
// child had written them. `bytes` may be `NULL` when `len` is 0.
//
// # Safety
//
// `term` is `NULL` or live; `bytes` points to `len` readable bytes.
tt_status tt_term_feed(const struct tt_term *term, const uint8_t *bytes, size_t len);

// Resizes the terminal to `cols` x `rows` cells: the primary screen and
// its history are rewrapped, the alternate screen is cut or padded. The
// child, if any, is told the new size (`width_px` and `height_px` are the
// view's size in pixels, 0 if unknown; they also give the cell size that
// image sizes are measured with) and output paused by
// `tt_term_resize_begin` flows again, whatever the outcome.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_resize(const struct tt_term *term,
                         uint16_t cols,
                         uint16_t rows,
                         uint16_t width_px,
                         uint16_t height_px);

// Frees the terminal. Also valid on a poisoned terminal; `NULL` is a
// no-op. No other call may use `term` during or after this one.
//
// # Safety
//
// `term` is `NULL` or live, and not used again.
void tt_term_free(struct tt_term *term);

// Copies the text of `rows` viewport rows from `row` into `buf`: UTF-8,
// one line per row joined by `\n` (line N is row `row + N`), wide
// characters once, blank and concealed (SGR 8) cells as spaces, trailing
// spaces trimmed, no NUL. `*len` becomes the text's length. When that is
// more than `cap`, nothing is copied and the answer is `TT_FULL`: call
// again with a larger buffer (pass `cap` 0 to ask for the length). Rows
// past the viewport are not read. `TT_INVALID` for a `NULL` `len`, or a
// `NULL` `buf` with a `cap`.
//
// # Safety
//
// `term` is `NULL` or live; `buf` is `NULL` or points to `cap` writable
// bytes; `len` is `NULL` or writable.
tt_status tt_term_read_text(const struct tt_term *term,
                            uint16_t row,
                            uint16_t rows,
                            uint8_t *buf,
                            size_t cap,
                            size_t *len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCULL_H */

/* The frame is read in place, so these layouts are the core's own. */
#ifdef __cplusplus
static_assert(sizeof(tt_cell) == 8, "tt_cell layout");
static_assert(sizeof(tt_run) == 16, "tt_run layout");
#else
_Static_assert(sizeof(tt_cell) == 8, "tt_cell layout");
_Static_assert(sizeof(tt_run) == 16, "tt_run layout");
#endif
