/*
 * Copyright (c) 2026 Ivan Tugay
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * Generated by cbindgen from crates/scull-ffi/src:
 * `just bindings`. Do not edit.
 */

#ifndef SCULL_H
#define SCULL_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

// Breaking changes bump the major version; a host refuses to run on
// another major.
#define TT_ABI_VERSION_MAJOR 0

// Additions (new functions, fields appended to a struct) bump the minor.
// While the major is 0 every minor may break, so the minor must match too.
#define TT_ABI_VERSION_MINOR 2

// The version a host was built against, `major << 16 | minor`; pass it
// in `tt_term_options.abi_version`.
#define TT_ABI_VERSION 2

// `tt_event.kind`: the program rang the bell, once or more since the last
// poll.
#define TT_EVENT_BELL 1

// `tt_event.kind`: the child ended and all its output has been parsed.
// Reported once, last.
#define TT_EVENT_CHILD_EXITED 2

// `tt_event.exit_code` when the system did not say. A literal, not the
// PTY crate's constant, so the generated header can spell it.
#define TT_EXIT_CODE_UNKNOWN 4294967295

// The cell holds more code points than `codepoint`; the whole cluster is
// in its row's text.
#define TT_CELL_CLUSTER 1

// A colour: `TT_COLOR_DEFAULT`, `TT_COLOR_INDEXED | index` or
// `TT_COLOR_RGB | 0xRRGGBB`; the kind is in `TT_COLOR_KIND_MASK`.
#define TT_COLOR_DEFAULT 0

// Palette colour, index in the low byte.
#define TT_COLOR_INDEXED 16777216

// True colour in the low three bytes.
#define TT_COLOR_RGB 33554432

// The bits that hold a colour's kind.
#define TT_COLOR_KIND_MASK 4278190080

// `tt_style.attrs` bits.
#define TT_ATTR_BOLD 1

// Faint.
#define TT_ATTR_DIM 2

// Italic.
#define TT_ATTR_ITALIC 4

// Blinking.
#define TT_ATTR_BLINK 8

// Foreground and background swapped.
#define TT_ATTR_INVERSE 16

// Invisible text.
#define TT_ATTR_HIDDEN 32

// Struck through.
#define TT_ATTR_STRIKE 64

// Line above.
#define TT_ATTR_OVERLINE 128

// `tt_style.underline` values.
#define TT_UNDERLINE_NONE 0

// One line.
#define TT_UNDERLINE_SINGLE 1

// Two lines.
#define TT_UNDERLINE_DOUBLE 2

// Wavy.
#define TT_UNDERLINE_CURLY 3

// Dotted.
#define TT_UNDERLINE_DOTTED 4

// Dashed.
#define TT_UNDERLINE_DASHED 5

// What every fallible call answers. Values are only ever appended.
enum tt_status
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  // Done.
  TT_OK = 0,
  // A `NULL` handle or pointer, a `struct_size` too small, a size of
  // zero, or text that is not UTF-8.
  TT_INVALID = 1,
  // The host was built against another ABI version.
  TT_ABI_MISMATCH = 2,
  // An earlier call panicked inside this terminal; only
  // `tt_term_free` is left to call.
  TT_POISONED = 3,
  // This call panicked inside the core; the terminal is now poisoned.
  TT_PANIC = 4,
  // Nothing to report: the event queue is empty.
  TT_EMPTY = 5,
  // The terminal has no child to talk to: it was made by
  // `tt_term_new`, or its child has gone.
  TT_CLOSED = 6,
  // The operating system refused: no PTY, a program that does not
  // start, a size the PTY rejects.
  TT_IO = 7,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum tt_status tt_status;
#else
typedef int32_t tt_status;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

// A UI-owned frame. Opaque to the host; one per view, used from one
// thread at a time.
typedef struct tt_frame tt_frame;

// An image's pixels, shared and immutable. Opaque to the host: read it
// with `tt_image_pixels`.
typedef struct tt_image tt_image;

// One terminal. Opaque to the host.
typedef struct tt_term tt_term;

// One event. A `u32` kind rather than an enum, so a kind added later is a
// value an older host skips, not undefined behaviour.
typedef struct tt_event {
  // `sizeof(tt_event)` as the host knows it.
  uint32_t struct_size;
  // One of `TT_EVENT_*`; skip kinds you do not know.
  uint32_t kind;
  // `TT_EVENT_CHILD_EXITED`: the exit code, or `TT_EXIT_CODE_UNKNOWN`.
  uint32_t exit_code;
  // `TT_EVENT_CHILD_EXITED`: 1 when a signal ended the child.
  uint8_t signaled;
} tt_event;

// The cursor in viewport rows.
typedef struct tt_cursor {
  // Viewport row.
  uint16_t row;
  // Column.
  uint16_t col;
  // 0 when hidden or scrolled out of the viewport.
  uint8_t visible;
} tt_cursor;

// One cell: 8 bytes, row after row, `cols * rows` of them.
typedef struct tt_cell {
  // The first code point of the cell's text; 0 when it shows none.
  uint32_t codepoint;
  // Index into `tt_frame_view.styles`.
  uint16_t style;
  // Columns covered: 1, 2 for a wide character, 0 for the cell behind it.
  uint8_t width;
  // `TT_CELL_CLUSTER` or 0.
  uint8_t flags;
} tt_cell;

// Neighbouring cells of one style and width with their text, the unit the
// platform shaper takes. Blank cells belong to no run.
typedef struct tt_run {
  // First column.
  uint16_t col;
  // Columns covered, wide spacers included.
  uint16_t cols;
  // Index into `tt_frame_view.styles`.
  uint16_t style;
  // Columns per character: 1 or 2.
  uint8_t width;
  // Byte offset of the run's text in its row's `text`.
  uint32_t text_start;
  // Byte length of the run's text.
  uint32_t text_len;
} tt_run;

// One viewport row: the line it shows and its text.
typedef struct tt_row {
  // The line shown; stays with the line as it scrolls, so it keys a
  // cache of shaped rows.
  uint64_t id;
  // Bumped by every change to the line.
  uint32_t generation;
  // The row's text runs, left to right.
  const struct tt_run *runs;
  // Number of runs.
  size_t runs_len;
  // UTF-8 text of all runs, not NUL-terminated.
  const uint8_t *text;
  // Bytes of text.
  size_t text_len;
} tt_row;

// A style as SGR set it; palette and reverse video are not resolved yet.
typedef struct tt_style {
  // Foreground colour.
  uint32_t fg;
  // Background colour.
  uint32_t bg;
  // Underline colour; `TT_COLOR_DEFAULT` follows the foreground.
  uint32_t underline_color;
  // `TT_ATTR_*` bits.
  uint16_t attrs;
  // A `TT_UNDERLINE_*` value.
  uint8_t underline;
} tt_style;

// Rows `start..end` are, unchanged, the rows from `from` of the previous
// picture: blit them before repainting the dirty rows.
typedef struct tt_scroll {
  // First row moved into.
  uint16_t start;
  // One past the last row moved into.
  uint16_t end;
  // Where `start` was in the previous picture.
  uint16_t from;
} tt_scroll;

// One image in the viewport. Draw the source rectangle of `image` scaled
// to `cols` x `rows` cells whose top-left cell is (`row`, `col`), moved by
// the pixel offset. Placements come lowest `z` first; a negative `z`
// draws below the text.
typedef struct tt_placement {
  // The pixels; valid until the next update or free of the frame, or
  // until `tt_image_release` after a `tt_image_retain`.
  const struct tt_image *image;
  // Changes whenever the pixels behind `image` may have; a texture cache
  // keys on `image` and `generation`.
  uint64_t generation;
  // Viewport row of the top-left cell; negative above the viewport.
  int32_t row;
  // Column of the top-left cell.
  uint32_t col;
  // Width in cells.
  uint32_t cols;
  // Height in cells.
  uint32_t rows;
  // Pixel offset inside the top-left cell.
  uint32_t offset_x;
  // Pixel offset inside the top-left cell.
  uint32_t offset_y;
  // Source rectangle in image pixels: left edge.
  uint32_t src_x;
  // Top edge.
  uint32_t src_y;
  // Width.
  uint32_t src_w;
  // Height.
  uint32_t src_h;
  // Stacking order.
  int32_t z;
} tt_placement;

// What `tt_frame_update` hands back. Set `struct_size` before the call.
typedef struct tt_frame_view {
  // `sizeof(tt_frame_view)` as the host knows it; on return, the bytes
  // the core filled in.
  uint32_t struct_size;
  // Columns.
  uint16_t cols;
  // Rows.
  uint16_t rows;
  // 0 while synchronized output (mode 2026) holds the picture: nothing
  // changed and there is no damage; keep showing the last frame.
  uint8_t updated;
  // 1 when every row must be repainted (first frame, resize, other
  // screen); every row is then also listed in `dirty`.
  uint8_t full;
  // The cursor.
  struct tt_cursor cursor;
  // `cols * rows` cells, row-major.
  const struct tt_cell *cells;
  // Number of cells.
  size_t cells_len;
  // One entry per viewport row.
  const struct tt_row *lines;
  // Number of rows in `lines`.
  size_t lines_len;
  // The style table that cells and runs index; entry 0 is the default.
  const struct tt_style *styles;
  // Number of styles.
  size_t styles_len;
  // Rows to blit from the previous picture, applied before `dirty`.
  const struct tt_scroll *scrolls;
  // Number of scrolls.
  size_t scrolls_len;
  // Rows to repaint, top to bottom.
  const uint16_t *dirty;
  // Number of dirty rows.
  size_t dirty_len;
  // The images in the viewport, lowest `z` first. The rows they cover
  // are in `dirty` whenever a placement over them changed.
  const struct tt_placement *placements;
  // Number of placements.
  size_t placements_len;
} tt_frame_view;

// UTF-8 text the host owns: `len` bytes at `ptr`, no terminator. `ptr`
// may be `NULL` when `len` is 0.
typedef struct tt_str {
  // The first byte.
  const uint8_t *ptr;
  // Bytes, not characters.
  size_t len;
} tt_str;

// Called with the `userdata` given at spawn when the terminal has
// something new: output to draw or an event to poll. It runs on a core
// thread and must not block, unwind or call any `tt_*` function: post a
// redraw to the UI thread and return. It is not called again until the
// host calls `tt_frame_update` or `tt_term_poll_event` on the terminal,
// and never after `tt_term_free` returns.
typedef void (*tt_wakeup_fn)(void *userdata);

// How to create a terminal. Fields a host does not know read as zero;
// `tt_term_new` reads only up to `scrollback`.
typedef struct tt_term_options {
  // `sizeof(tt_term_options)` as the host knows it.
  uint32_t struct_size;
  // `TT_ABI_VERSION` as the host was built with it.
  uint32_t abi_version;
  // Columns, at least 1.
  uint16_t cols;
  // Rows, at least 1.
  uint16_t rows;
  // History rows to keep; the core clamps it.
  uint32_t scrollback;
  // The program, searched on `PATH`; empty runs the user's shell.
  struct tt_str program;
  // `args_len` arguments; ignored for the user's shell.
  const struct tt_str *args;
  // Number of `args`.
  size_t args_len;
  // Working directory; empty keeps the host's.
  struct tt_str cwd;
  // `env_len` `NAME=value` entries added to the host's environment.
  const struct tt_str *env;
  // Number of `env`.
  size_t env_len;
  // Called from a core thread when there is something new to draw or
  // poll; `NULL` for none. See `tt_wakeup_fn`.
  tt_wakeup_fn wakeup;
  // Passed to `wakeup` as is.
  void *userdata;
} tt_term_options;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// The ABI version of this library, `major << 16 | minor`.
uint32_t tt_abi_version(void);

// Takes the next event into `*event`: `TT_OK` with one, `TT_EMPTY` when
// there is none. Call it until `TT_EMPTY` after every wakeup.
//
// # Safety
//
// `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
// writable bytes.
tt_status tt_term_poll_event(const struct tt_term *term, struct tt_event *event);

// A new, empty frame; the first update fills it. `NULL` only if the core
// failed. Free it with `tt_frame_free`.
struct tt_frame *tt_frame_new(void);

// Brings `frame` up to date with `term`'s viewport and describes it in
// `*view`. Holds the terminal lock only while it copies the rows that
// changed. The pointers in `*view` stay valid until the next update or
// free of this frame.
//
// # Safety
//
// `frame` and `term` are `NULL` or live; `view` is `NULL` or points to
// `struct_size` writable bytes. No other thread uses `frame` meanwhile.
tt_status tt_frame_update(struct tt_frame *frame,
                          const struct tt_term *term,
                          struct tt_frame_view *view);

// Frees the frame and every buffer its views pointed to. `NULL` is a
// no-op.
//
// # Safety
//
// `frame` is `NULL` or live, and not used again.
void tt_frame_free(struct tt_frame *frame);

// Takes a reference to `image`, so its pixels outlive the frame update
// that handed it out. `NULL` is a no-op.
//
// # Safety
//
// `image` is `NULL`, a `tt_placement.image` whose view is still valid, or
// an image retained and not yet released. Any thread may call this.
void tt_image_retain(const struct tt_image *image);

// Drops a reference taken by `tt_image_retain`. `NULL` is a no-op.
//
// # Safety
//
// `image` is `NULL` or was retained, and each retain is released once.
void tt_image_release(const struct tt_image *image);

// The pixels of `image`: `height` rows of `stride` bytes, each `width`
// RGBA pixels of 4 bytes, straight (not premultiplied) alpha. Valid while
// `image` is. Each out pointer may be `NULL`; a `NULL` image answers
// `NULL` and zeroes them.
//
// # Safety
//
// `image` is as for `tt_image_retain`; each out pointer is `NULL` or
// writable.
const uint8_t *tt_image_pixels(const struct tt_image *image,
                               uint32_t *width,
                               uint32_t *height,
                               size_t *stride);

// Creates a terminal running a child on a new PTY: `options.program`
// with its arguments, or the user's shell. Output is parsed on core
// threads; `options.wakeup` says when to look. On `TT_OK` `*out` holds
// the handle; free it with `tt_term_free`, which ends the child.
//
// # Safety
//
// As for `tt_term_new`; the strings and arrays in `*options` are valid
// for their lengths, during this call only.
tt_status tt_term_spawn(const struct tt_term_options *options, struct tt_term **out);

// Queues `len` bytes of input (keys, paste) for the child without
// blocking. `*written` gets how many leading bytes were taken: fewer than
// `len` when the child is not reading; offer the rest later. `TT_CLOSED`
// when there is no child or it has gone.
//
// # Safety
//
// `term` is `NULL` or live; `bytes` points to `len` readable bytes;
// `written` is `NULL` or writable.
tt_status tt_term_write(const struct tt_term *term,
                        const uint8_t *bytes,
                        size_t len,
                        size_t *written);

// Starts an interactive resize: the child's output is held back, so the
// host keeps drawing the last frame, until `tt_term_resize` with the final
// size. Without it every intermediate size would rewrap the history.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_resize_begin(const struct tt_term *term);

// Creates a terminal with no child process: bytes reach it only through
// `tt_term_feed`. On `TT_OK` `*out` holds the handle; free it with
// `tt_term_free`.
//
// # Safety
//
// `options` is `NULL` or points to `struct_size` readable bytes; `out` is
// `NULL` or writable.
tt_status tt_term_new(const struct tt_term_options *options, struct tt_term **out);

// Parses `len` bytes of program output into the terminal, as if the
// child had written them. `bytes` may be `NULL` when `len` is 0.
//
// # Safety
//
// `term` is `NULL` or live; `bytes` points to `len` readable bytes.
tt_status tt_term_feed(const struct tt_term *term, const uint8_t *bytes, size_t len);

// Resizes the terminal to `cols` x `rows` cells: the primary screen and
// its history are rewrapped, the alternate screen is cut or padded. The
// child, if any, is told the new size (`width_px` and `height_px` are the
// view's size in pixels, 0 if unknown; they also give the cell size that
// image sizes are measured with) and output paused by
// `tt_term_resize_begin` flows again, whatever the outcome.
//
// # Safety
//
// `term` is `NULL` or live.
tt_status tt_term_resize(const struct tt_term *term,
                         uint16_t cols,
                         uint16_t rows,
                         uint16_t width_px,
                         uint16_t height_px);

// Frees the terminal. Also valid on a poisoned terminal; `NULL` is a
// no-op. No other call may use `term` during or after this one.
//
// # Safety
//
// `term` is `NULL` or live, and not used again.
void tt_term_free(struct tt_term *term);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SCULL_H */

/* The frame is read in place, so these layouts are the core's own. */
#ifdef __cplusplus
static_assert(sizeof(tt_cell) == 8, "tt_cell layout");
static_assert(sizeof(tt_run) == 16, "tt_run layout");
#else
_Static_assert(sizeof(tt_cell) == 8, "tt_cell layout");
_Static_assert(sizeof(tt_run) == 16, "tt_run layout");
#endif
