//! The committed C header and C# bindings are what cbindgen and csbindgen
//! generate from the exports now; `SCULL_BLESS=1` rewrites them
//! (`just bindings`). A test rather than a script so `just check` catches
//! a stale header on every platform with no tool to install. The pattern
//! is ketch-capi's header drift test, by the same author.

// Helpers outside #[test] functions are still test code; a failure here should abort loudly.
#![allow(clippy::unwrap_used, clippy::panic)]

use std::path::{Path, PathBuf};

/// Every module with exports. csbindgen reads each file alone; cbindgen
/// follows `mod` items from the crate root by itself.
const SOURCES: [&str; 9] = [
    "src/lib.rs",
    "src/config.rs",
    "src/guard.rs",
    "src/term.rs",
    "src/spawn.rs",
    "src/event.rs",
    "src/frame.rs",
    "src/input.rs",
    "src/text.rs",
];

fn crate_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Compares `rendered` with the committed `relative`, or rewrites it under
/// `SCULL_BLESS`.
fn check_drift(relative: &str, rendered: &str) {
    let path = crate_dir().join(relative);
    if std::env::var_os("SCULL_BLESS").is_some() {
        std::fs::write(&path, rendered).unwrap();
        return;
    }
    // A Windows checkout may have turned LF into CRLF, in the committed
    // file and in inputs such as cbindgen.toml's header; the text is the same.
    let committed = std::fs::read_to_string(&path)
        .unwrap_or_default()
        .replace("\r\n", "\n");
    assert!(
        committed == rendered.replace("\r\n", "\n"),
        "{relative} is stale: run `just bindings`"
    );
}

#[test]
fn the_committed_c_header_is_what_cbindgen_generates() {
    let config = cbindgen::Config::from_file(crate_dir().join("cbindgen.toml")).unwrap();
    let mut rendered = Vec::new();
    cbindgen::Builder::new()
        .with_config(config)
        .with_src(crate_dir().join("src/lib.rs"))
        .generate()
        .unwrap()
        .write(&mut rendered);
    check_drift("include/scull.h", &String::from_utf8(rendered).unwrap());
}

#[test]
fn the_committed_csharp_bindings_are_what_csbindgen_generates() {
    let out = Path::new(env!("CARGO_TARGET_TMPDIR")).join("NativeMethods.g.cs");
    SOURCES
        .iter()
        .fold(csbindgen::Builder::new(), |b, src| {
            b.input_extern_file(crate_dir().join(src))
        })
        .csharp_dll_name("scull_ffi")
        .csharp_namespace("Scull.Native")
        .csharp_class_name("NativeMethods")
        .csharp_generate_const_filter(|name| name.starts_with("TT_"))
        .csharp_file_header(
            "// Copyright (c) 2026 Ivan Tugay\n\
             // SPDX-License-Identifier: GPL-3.0-or-later\n\
             // Generated by csbindgen from crates/scull-ffi/src: `just bindings`. Do not edit.",
        )
        .generate_csharp_file(&out)
        .unwrap();
    let rendered = std::fs::read_to_string(&out).unwrap();
    check_drift("bindings/csharp/NativeMethods.g.cs", &rendered);
}
