//! Unicode width and grapheme-break tables generated from the Unicode data
//! files. A leaf crate so the scanner and the grid share one width function
//! and can never disagree about how many cells a character takes.
//!
//! The terminal feeds each printable code point to a [`GraphemeState`]; when
//! it reports no boundary, the code point joins the previous cell and a
//! [`ClusterWidth`] says whether that cell grows or shrinks. DEC private
//! mode 2027 only switches the [`ClusterPolicy`]: segmentation always runs.
//!
//! The tables in `tables.rs` are generated by `tools/scull-ucd-gen`; run
//! `just ucd` after changing the generator.

mod grapheme;
mod props;
#[rustfmt::skip]
mod tables;
mod width;

pub use grapheme::GraphemeState;
pub use props::UnicodeVersion;
pub use width::{AmbiguousWidth, ClusterPolicy, ClusterWidth, WidthOptions, cluster_width, width};
