// Copyright (c) 2026 Ivan Tugay
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by csbindgen from crates/scull-ffi/src: `just bindings`. Do not edit.
// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Scull.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "scull_ffi";

        /// <summary>
        ///  Breaking changes bump the major version; a host refuses to run on
        ///  another major.
        /// </summary>
        internal const uint TT_ABI_VERSION_MAJOR = 0;
        /// <summary>
        ///  Additions (new functions, fields appended to a struct) bump the minor.
        ///  While the major is 0 every minor may break, so the minor must match too.
        /// </summary>
        internal const uint TT_ABI_VERSION_MINOR = 5;
        /// <summary>
        ///  The version a host was built against, `major &lt;&lt; 16 | minor`; pass it
        ///  in `tt_term_options.abi_version`.
        /// </summary>
        internal const uint TT_ABI_VERSION = 5;
        /// <summary>
        ///  `tt_keybind.action`: paste the clipboard.
        /// </summary>
        internal const byte TT_ACTION_PASTE = 1;
        /// <summary>
        ///  Make the font one point larger.
        /// </summary>
        internal const byte TT_ACTION_FONT_LARGER = 2;
        /// <summary>
        ///  Make the font one point smaller.
        /// </summary>
        internal const byte TT_ACTION_FONT_SMALLER = 3;
        /// <summary>
        ///  Back to the configured font size.
        /// </summary>
        internal const byte TT_ACTION_FONT_RESET = 4;
        /// <summary>
        ///  Scroll the history one screen up.
        /// </summary>
        internal const byte TT_ACTION_SCROLL_PAGE_UP = 5;
        /// <summary>
        ///  Scroll the history one screen down.
        /// </summary>
        internal const byte TT_ACTION_SCROLL_PAGE_DOWN = 6;
        /// <summary>
        ///  Scroll to the oldest history row.
        /// </summary>
        internal const byte TT_ACTION_SCROLL_TO_TOP = 7;
        /// <summary>
        ///  Scroll back to the screen.
        /// </summary>
        internal const byte TT_ACTION_SCROLL_TO_BOTTOM = 8;
        /// <summary>
        ///  `tt_event.kind`: the program rang the bell, once or more since the last
        ///  poll.
        /// </summary>
        internal const uint TT_EVENT_BELL = 1;
        /// <summary>
        ///  `tt_event.kind`: the child ended and all its output has been parsed.
        ///  Reported once, last.
        /// </summary>
        internal const uint TT_EVENT_CHILD_EXITED = 2;
        /// <summary>
        ///  `tt_event.exit_code` when the system did not say. A literal, not the
        ///  PTY crate's constant, so the generated header can spell it.
        /// </summary>
        internal const uint TT_EXIT_CODE_UNKNOWN = 4294967295;
        /// <summary>
        ///  The cell holds more code points than `codepoint`; the whole cluster is
        ///  in its row's text.
        /// </summary>
        internal const byte TT_CELL_CLUSTER = 1;
        /// <summary>
        ///  A colour: `TT_COLOR_DEFAULT`, `TT_COLOR_INDEXED | index` or
        ///  `TT_COLOR_RGB | 0xRRGGBB`; the kind is in `TT_COLOR_KIND_MASK`.
        /// </summary>
        internal const uint TT_COLOR_DEFAULT = 0;
        /// <summary>
        ///  Palette colour, index in the low byte.
        /// </summary>
        internal const uint TT_COLOR_INDEXED = 16777216;
        /// <summary>
        ///  True colour in the low three bytes.
        /// </summary>
        internal const uint TT_COLOR_RGB = 33554432;
        /// <summary>
        ///  The bits that hold a colour's kind.
        /// </summary>
        internal const uint TT_COLOR_KIND_MASK = 4278190080;
        /// <summary>
        ///  `tt_style.attrs` bits.
        /// </summary>
        internal const ushort TT_ATTR_BOLD = 1;
        /// <summary>
        ///  Faint.
        /// </summary>
        internal const ushort TT_ATTR_DIM = 2;
        /// <summary>
        ///  Italic.
        /// </summary>
        internal const ushort TT_ATTR_ITALIC = 4;
        /// <summary>
        ///  Blinking.
        /// </summary>
        internal const ushort TT_ATTR_BLINK = 8;
        /// <summary>
        ///  Foreground and background swapped.
        /// </summary>
        internal const ushort TT_ATTR_INVERSE = 16;
        /// <summary>
        ///  Invisible text.
        /// </summary>
        internal const ushort TT_ATTR_HIDDEN = 32;
        /// <summary>
        ///  Struck through.
        /// </summary>
        internal const ushort TT_ATTR_STRIKE = 64;
        /// <summary>
        ///  Line above.
        /// </summary>
        internal const ushort TT_ATTR_OVERLINE = 128;
        /// <summary>
        ///  `tt_style.underline` values.
        /// </summary>
        internal const byte TT_UNDERLINE_NONE = 0;
        /// <summary>
        ///  One line.
        /// </summary>
        internal const byte TT_UNDERLINE_SINGLE = 1;
        /// <summary>
        ///  Two lines.
        /// </summary>
        internal const byte TT_UNDERLINE_DOUBLE = 2;
        /// <summary>
        ///  Wavy.
        /// </summary>
        internal const byte TT_UNDERLINE_CURLY = 3;
        /// <summary>
        ///  Dotted.
        /// </summary>
        internal const byte TT_UNDERLINE_DOTTED = 4;
        /// <summary>
        ///  Dashed.
        /// </summary>
        internal const byte TT_UNDERLINE_DASHED = 5;
        /// <summary>
        ///  Most bytes of composing text a frame shows.
        /// </summary>
        internal const nuint TT_MAX_PREEDIT_BYTES = 1024;
        /// <summary>
        ///  `tt_key_event.action`: the key went down.
        /// </summary>
        internal const byte TT_KEY_PRESS = 1;
        /// <summary>
        ///  The key auto-repeats.
        /// </summary>
        internal const byte TT_KEY_REPEAT = 2;
        /// <summary>
        ///  The key went up.
        /// </summary>
        internal const byte TT_KEY_RELEASE = 3;
        /// <summary>
        ///  `tt_key_event.mods` and `tt_mouse_event.mods` bits.
        /// </summary>
        internal const byte TT_MOD_SHIFT = 1;
        /// <summary>
        ///  Alt, Option on macOS.
        /// </summary>
        internal const byte TT_MOD_ALT = 2;
        /// <summary>
        ///  Control.
        /// </summary>
        internal const byte TT_MOD_CTRL = 4;
        /// <summary>
        ///  Super: Command on macOS, the Windows key.
        /// </summary>
        internal const byte TT_MOD_SUPER = 8;
        /// <summary>
        ///  Hyper.
        /// </summary>
        internal const byte TT_MOD_HYPER = 16;
        /// <summary>
        ///  Meta.
        /// </summary>
        internal const byte TT_MOD_META = 32;
        /// <summary>
        ///  Caps Lock is on.
        /// </summary>
        internal const byte TT_MOD_CAPS_LOCK = 64;
        /// <summary>
        ///  Num Lock is on.
        /// </summary>
        internal const byte TT_MOD_NUM_LOCK = 128;
        /// <summary>
        ///  `tt_key_event.key`: Escape. The keys after it, one code each, are
        ///  Enter, Tab, Backspace, Insert, Delete, Left, Right, Up, Down, Page Up,
        ///  Page Down, Home and End (`TT_KEY_END`).
        /// </summary>
        internal const uint TT_KEY_ESCAPE = 57344;
        /// <summary>
        ///  The last of the keys from `TT_KEY_ESCAPE`.
        /// </summary>
        internal const uint TT_KEY_END = 57357;
        /// <summary>
        ///  Caps Lock; then Scroll Lock, Num Lock, Print Screen, Pause, Menu.
        /// </summary>
        internal const uint TT_KEY_CAPS_LOCK = 57358;
        /// <summary>
        ///  F1; F`n` is `TT_KEY_F1 + n - 1` up to F35.
        /// </summary>
        internal const uint TT_KEY_F1 = 57364;
        /// <summary>
        ///  Keypad 0; then 1 to 9, Decimal, Divide, Multiply, Subtract, Add, Enter,
        ///  Equal, Separator, Left, Right, Up, Down, Page Up, Page Down, Home, End,
        ///  Insert, Delete, Begin.
        /// </summary>
        internal const uint TT_KEY_KP_0 = 57399;
        /// <summary>
        ///  Play; then Pause, Play/Pause, Reverse, Stop, Fast Forward, Rewind, Next
        ///  Track, Previous Track, Record, Volume Down, Volume Up, Mute.
        /// </summary>
        internal const uint TT_KEY_MEDIA_PLAY = 57428;
        /// <summary>
        ///  Left Shift on its own; then Left Control, Left Alt, Left Super, Left
        ///  Hyper, Left Meta, the same six on the right, ISO Level 3 Shift and ISO
        ///  Level 5 Shift.
        /// </summary>
        internal const uint TT_KEY_LEFT_SHIFT = 57441;
        /// <summary>
        ///  `tt_mouse_event.action`: a button went down; wheel steps are presses.
        /// </summary>
        internal const byte TT_MOUSE_PRESS = 1;
        /// <summary>
        ///  A button went up.
        /// </summary>
        internal const byte TT_MOUSE_RELEASE = 2;
        /// <summary>
        ///  The pointer moved to another cell, or pixel while the program asks
        ///  for pixels; send it only then.
        /// </summary>
        internal const byte TT_MOUSE_MOTION = 3;
        /// <summary>
        ///  `tt_mouse_event.button`: none, for motion with no button held. Others
        ///  are X11's numbers: 1 left, 2 middle, 3 right, 4 to 7 wheel up, down,
        ///  left and right, 8 back, 9 forward, 10 and 11.
        /// </summary>
        internal const byte TT_MOUSE_NONE = 0;
        /// <summary>
        ///  The left button.
        /// </summary>
        internal const byte TT_MOUSE_LEFT = 1;
        /// <summary>
        ///  The middle button.
        /// </summary>
        internal const byte TT_MOUSE_MIDDLE = 2;
        /// <summary>
        ///  The right button.
        /// </summary>
        internal const byte TT_MOUSE_RIGHT = 3;
        /// <summary>
        ///  One wheel step up.
        /// </summary>
        internal const byte TT_MOUSE_WHEEL_UP = 4;
        /// <summary>
        ///  One wheel step down.
        /// </summary>
        internal const byte TT_MOUSE_WHEEL_DOWN = 5;
        /// <summary>
        ///  One wheel step left.
        /// </summary>
        internal const byte TT_MOUSE_WHEEL_LEFT = 6;
        /// <summary>
        ///  One wheel step right.
        /// </summary>
        internal const byte TT_MOUSE_WHEEL_RIGHT = 7;




        /// <summary>
        ///  The ABI version of this library, `major &lt;&lt; 16 | minor`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint tt_abi_version();

        /// <summary>
        ///  Opens the configuration and starts watching it. A missing file is the
        ///  defaults and a broken one is an `error` in the view, so this fails only
        ///  for bad arguments or a host with no home directory to put the file in.
        ///  On `TT_OK` `*out` holds the handle; free it with `tt_config_free`.
        ///
        ///  # Safety
        ///
        ///  `options` is `NULL` or points to `struct_size` readable bytes, its
        ///  strings valid for their lengths during this call; `out` is `NULL` or
        ///  writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_config_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_config_new(tt_config_options* options, tt_config** @out);

        /// <summary>
        ///  Fills `*view` with the settings in force and sets `updated` when they
        ///  are not what the previous poll returned. Polling lets the next wakeup
        ///  fire.
        ///
        ///  # Safety
        ///
        ///  `config` is `NULL` or live; `view` is `NULL` or points to `struct_size`
        ///  writable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_config_poll", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_config_poll(tt_config* config, tt_config_view* view);

        /// <summary>
        ///  Changes one setting in the config file, keeping the rest of the file as
        ///  it is, and applies it at once. `key` is one of `font.family`,
        ///  `font.size`, `colors.scheme`, `colors.foreground`, `colors.background`,
        ///  `colors.cursor`, `scrollback`; `value` is its text (`13.5`,
        ///  `solarized-dark`, `#1a2b3c`), and an empty `value` removes the key so its
        ///  default applies. `TT_INVALID` for an unknown key or a value the config
        ///  does not accept, with the file untouched; `TT_IO` when it cannot be
        ///  written.
        ///
        ///  # Safety
        ///
        ///  `config` is `NULL` or live; the strings are valid for their lengths.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_config_set", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_config_set(tt_config* config, tt_str key, tt_str value);

        /// <summary>
        ///  Frees the configuration and stops its watcher. `NULL` is a no-op. No
        ///  other call may use `config` during or after this one.
        ///
        ///  # Safety
        ///
        ///  `config` is `NULL` or live, and not used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_config_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_config_free(tt_config* config);

        /// <summary>
        ///  Creates a terminal with no child process: bytes reach it only through
        ///  `tt_term_feed`. On `TT_OK` `*out` holds the handle; free it with
        ///  `tt_term_free`.
        ///
        ///  # Safety
        ///
        ///  `options` is `NULL` or points to `struct_size` readable bytes; `out` is
        ///  `NULL` or writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_new(tt_term_options* options, tt_term** @out);

        /// <summary>
        ///  Parses `len` bytes of program output into the terminal, as if the
        ///  child had written them. `bytes` may be `NULL` when `len` is 0.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `bytes` points to `len` readable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_feed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_feed(tt_term* term, byte* bytes, nuint len);

        /// <summary>
        ///  Resizes the terminal to `cols` x `rows` cells: the primary screen and
        ///  its history are rewrapped, the alternate screen is cut or padded. The
        ///  child, if any, is told the new size (`width_px` and `height_px` are the
        ///  view's size in pixels, 0 if unknown; they also give the cell size that
        ///  image sizes are measured with) and output paused by
        ///  `tt_term_resize_begin` flows again, whatever the outcome.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_resize(tt_term* term, ushort cols, ushort rows, ushort width_px, ushort height_px);

        /// <summary>
        ///  Frees the terminal. Also valid on a poisoned terminal; `NULL` is a
        ///  no-op. No other call may use `term` during or after this one.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live, and not used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_term_free(tt_term* term);

        /// <summary>
        ///  Creates a terminal running a child on a new PTY: `options.program`
        ///  with its arguments, or the user's shell. Output is parsed on core
        ///  threads; `options.wakeup` says when to look. On `TT_OK` `*out` holds
        ///  the handle; free it with `tt_term_free`, which ends the child.
        ///
        ///  # Safety
        ///
        ///  As for `tt_term_new`; the strings and arrays in `*options` are valid
        ///  for their lengths, during this call only.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_spawn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_spawn(tt_term_options* options, tt_term** @out);

        /// <summary>
        ///  Queues `len` bytes of input (keys, paste) for the child without
        ///  blocking. `*written` gets how many leading bytes were taken: fewer than
        ///  `len` when the child is not reading; offer the rest later. `TT_CLOSED`
        ///  when there is no child or it has gone.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `bytes` points to `len` readable bytes;
        ///  `written` is `NULL` or writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_write(tt_term* term, byte* bytes, nuint len, nuint* written);

        /// <summary>
        ///  Starts an interactive resize: the child's output is held back, so the
        ///  host keeps drawing the last frame, until `tt_term_resize` with the final
        ///  size. Without it every intermediate size would rewrap the history.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_resize_begin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_resize_begin(tt_term* term);

        /// <summary>
        ///  Takes the next event into `*event`: `TT_OK` with one, `TT_EMPTY` when
        ///  there is none. Call it until `TT_EMPTY` after every wakeup.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
        ///  writable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_poll_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_poll_event(tt_term* term, tt_event* @event);

        /// <summary>
        ///  A new, empty frame; the first update fills it. `NULL` only if the core
        ///  failed. Free it with `tt_frame_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_frame* tt_frame_new();

        /// <summary>
        ///  Brings `frame` up to date with `term`'s viewport and describes it in
        ///  `*view`. Holds the terminal lock only while it copies the rows that
        ///  changed. The pointers in `*view` stay valid until the next update or
        ///  free of this frame.
        ///
        ///  # Safety
        ///
        ///  `frame` and `term` are `NULL` or live; `view` is `NULL` or points to
        ///  `struct_size` writable bytes. No other thread uses `frame` meanwhile.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_frame_update(tt_frame* frame, tt_term* term, tt_frame_view* view);

        /// <summary>
        ///  Sets the input method's composing text, UTF-8, with the caret at byte
        ///  `caret` (moved back onto a character boundary); `len` 0 clears it. The
        ///  next `tt_frame_update` shows it at the cursor (`tt_frame_view.preedit`).
        ///  It never reaches the child: commit text with `tt_term_text`. Text past
        ///  `TT_MAX_PREEDIT_BYTES` is cut. `TT_INVALID` for a `NULL` frame or text
        ///  that is not UTF-8.
        ///
        ///  # Safety
        ///
        ///  `frame` is `NULL` or live and not used by another thread meanwhile;
        ///  `bytes` points to `len` readable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_preedit", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_frame_preedit(tt_frame* frame, byte* bytes, nuint len, nuint caret);

        /// <summary>
        ///  Frees the frame and every buffer its views pointed to. `NULL` is a
        ///  no-op.
        ///
        ///  # Safety
        ///
        ///  `frame` is `NULL` or live, and not used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_frame_free(tt_frame* frame);

        /// <summary>
        ///  Takes a reference to `image`, so its pixels outlive the frame update
        ///  that handed it out. `NULL` is a no-op.
        ///
        ///  # Safety
        ///
        ///  `image` is `NULL`, a `tt_placement.image` whose view is still valid, or
        ///  an image retained and not yet released. Any thread may call this.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_image_retain", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_image_retain(tt_image* image);

        /// <summary>
        ///  Drops a reference taken by `tt_image_retain`. `NULL` is a no-op.
        ///
        ///  # Safety
        ///
        ///  `image` is `NULL` or was retained, and each retain is released once.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_image_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_image_release(tt_image* image);

        /// <summary>
        ///  The pixels of `image`: `height` rows of `stride` bytes, each `width`
        ///  RGBA pixels of 4 bytes, straight (not premultiplied) alpha. Valid while
        ///  `image` is. Each out pointer may be `NULL`; a `NULL` image answers
        ///  `NULL` and zeroes them.
        ///
        ///  # Safety
        ///
        ///  `image` is as for `tt_image_retain`; each out pointer is `NULL` or
        ///  writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_image_pixels", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern byte* tt_image_pixels(tt_image* image, uint* width, uint* height, nuint* stride);

        /// <summary>
        ///  Sends a key event. `TT_OK` also when the active modes send nothing
        ///  for it (a release in legacy mode, a composing key); `TT_CLOSED` when
        ///  there is no child; `TT_FULL` when the child is not reading and its
        ///  input queue lacks room, in which case nothing was sent.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
        ///  readable bytes whose `text` is valid for its length.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_key", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_key(tt_term* term, tt_key_event* @event);

        /// <summary>
        ///  Sends text an input method committed outside a key event (dictation,
        ///  the character viewer). Control characters are dropped. Statuses as for
        ///  `tt_term_key`; `TT_INVALID` for text that is not UTF-8.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `bytes` points to `len` readable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_text(tt_term* term, byte* bytes, nuint len);

        /// <summary>
        ///  Sends pasted text: bracketed, with any bracket marker inside removed,
        ///  while the program asks for it (mode 2004); otherwise line feeds become
        ///  carriage returns. A paste is sent whole or not at all, so one larger
        ///  than the child's input queue (256 KiB) answers `TT_FULL`. Statuses
        ///  otherwise as for `tt_term_text`.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `bytes` points to `len` readable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_paste", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_paste(tt_term* term, byte* bytes, nuint len);

        /// <summary>
        ///  Tells the program the view gained (`focused` 1) or lost (0) focus,
        ///  while it asks for focus reports (mode 1004). Statuses as for
        ///  `tt_term_key`.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_focus", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_focus(tt_term* term, byte focused);

        /// <summary>
        ///  Sends a mouse event if the program takes it. `*taken`, unless `NULL`,
        ///  becomes 1 when it does: always while it tracks the mouse, and for a
        ///  wheel step on the alternate screen, which becomes a cursor key (mode
        ///  1007). At 0 the event is the host's: select, or scroll the history
        ///  with `tt_term_scroll_display`. Statuses as for `tt_term_key`.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
        ///  readable bytes; `taken` is `NULL` or writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_mouse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_mouse(tt_term* term, tt_mouse_event* @event, byte* taken);

        /// <summary>
        ///  Moves the viewport `delta` rows back into history (negative: towards
        ///  the screen), clamped to what history holds. Typing, text and paste
        ///  bring it back to the screen by themselves.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_scroll_display", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_scroll_display(tt_term* term, int delta);

        /// <summary>
        ///  Copies the text of `rows` viewport rows from `row` into `buf`: UTF-8,
        ///  one line per row joined by `\n` (line N is row `row + N`), wide
        ///  characters once, blank and concealed (SGR 8) cells as spaces, trailing
        ///  spaces trimmed, no NUL. `*len` becomes the text's length. When that is
        ///  more than `cap`, nothing is copied and the answer is `TT_FULL`: call
        ///  again with a larger buffer (pass `cap` 0 to ask for the length). Rows
        ///  past the viewport are not read. `TT_INVALID` for a `NULL` `len`, or a
        ///  `NULL` `buf` with a `cap`.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `buf` is `NULL` or points to `cap` writable
        ///  bytes; `len` is `NULL` or writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_read_text", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_read_text(tt_term* term, ushort row, ushort rows, byte* buf, nuint cap, nuint* len);


    }

    /// <summary>
    ///  How to open the configuration.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_config_options
    {
        /// <summary>
        ///  `sizeof(tt_config_options)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  `TT_ABI_VERSION` as the host was built with it.
        /// </summary>
        public uint abi_version;
        /// <summary>
        ///  The config file; empty for the default place
        ///  (`$XDG_CONFIG_HOME/scull/config.toml`, `~/.config/scull/config.toml`,
        ///  `%APPDATA%\scull\config.toml`).
        /// </summary>
        public tt_str path;
        /// <summary>
        ///  Called from a core thread when `tt_config_poll` would answer
        ///  something new; `NULL` for none. Same contract as `tt_wakeup_fn`:
        ///  it must not block or call `tt_*`, it is not called again until the
        ///  host polls, and never after `tt_config_free` returns.
        /// </summary>
        public delegate* unmanaged[Cdecl]<void*, void> wakeup;
        /// <summary>
        ///  Passed to `wakeup` as is.
        /// </summary>
        public void* userdata;
    }

    /// <summary>
    ///  A key binding: when `key` is pressed with exactly `mods` among Shift,
    ///  Alt, Control and Super held, do `action`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_keybind
    {
        /// <summary>
        ///  As `tt_key_event.key`.
        /// </summary>
        public uint key;
        /// <summary>
        ///  `TT_MOD_*` bits.
        /// </summary>
        public byte mods;
        /// <summary>
        ///  `TT_ACTION_*`.
        /// </summary>
        public byte action;
    }

    /// <summary>
    ///  The settings in force. Every pointer in it stays valid until the next
    ///  `tt_config_poll` or `tt_config_free` on the same handle.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_config_view
    {
        /// <summary>
        ///  `sizeof(tt_config_view)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  1 when anything changed since the previous poll (always on the first).
        /// </summary>
        public byte updated;
        /// <summary>
        ///  1 when file changes are watched; 0 means only `tt_config_set` and a
        ///  new handle see the file.
        /// </summary>
        public byte watching;
        /// <summary>
        ///  Grows with every change of the settings or of `error`.
        /// </summary>
        public ulong generation;
        /// <summary>
        ///  The font family; empty for the platform's monospace font.
        /// </summary>
        public tt_str font_family;
        /// <summary>
        ///  The font size in points.
        /// </summary>
        public float font_size;
        /// <summary>
        ///  History rows for terminals opened from now on.
        /// </summary>
        public uint scrollback;
        /// <summary>
        ///  The colour scheme's name as the file spells it (`scull-dark`, ...).
        /// </summary>
        public tt_str scheme;
        /// <summary>
        ///  Default text colour, `0xRRGGBB`.
        /// </summary>
        public uint foreground;
        /// <summary>
        ///  Default background colour, `0xRRGGBB`.
        /// </summary>
        public uint background;
        /// <summary>
        ///  Cursor colour, `0xRRGGBB`.
        /// </summary>
        public uint cursor;
        /// <summary>
        ///  Palette entries 0 to 15, `0xRRGGBB`.
        /// </summary>
        public fixed uint ansi[16];
        /// <summary>
        ///  The key bindings in force.
        /// </summary>
        public tt_keybind* keybinds;
        /// <summary>
        ///  Number of `keybinds`.
        /// </summary>
        public nuint keybinds_len;
        /// <summary>
        ///  Why the file could not be used the last time it was read, with its
        ///  name; empty when it was fine. The settings above are then the last
        ///  good ones.
        /// </summary>
        public tt_str error;
        /// <summary>
        ///  The config file's path.
        /// </summary>
        public tt_str path;
    }

    /// <summary>
    ///  The configuration. Opaque to the host.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_config
    {
    }

    /// <summary>
    ///  How to create a terminal. Fields a host does not know read as zero;
    ///  `tt_term_new` reads only up to `scrollback`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_term_options
    {
        /// <summary>
        ///  `sizeof(tt_term_options)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  `TT_ABI_VERSION` as the host was built with it.
        /// </summary>
        public uint abi_version;
        /// <summary>
        ///  Columns, at least 1.
        /// </summary>
        public ushort cols;
        /// <summary>
        ///  Rows, at least 1.
        /// </summary>
        public ushort rows;
        /// <summary>
        ///  History rows to keep; the core clamps it.
        /// </summary>
        public uint scrollback;
        /// <summary>
        ///  The program, searched on `PATH`; empty runs the user's shell.
        /// </summary>
        public tt_str program;
        /// <summary>
        ///  `args_len` arguments; ignored for the user's shell.
        /// </summary>
        public tt_str* args;
        /// <summary>
        ///  Number of `args`.
        /// </summary>
        public nuint args_len;
        /// <summary>
        ///  Working directory; empty keeps the host's.
        /// </summary>
        public tt_str cwd;
        /// <summary>
        ///  `env_len` `NAME=value` entries added to the host's environment.
        /// </summary>
        public tt_str* env;
        /// <summary>
        ///  Number of `env`.
        /// </summary>
        public nuint env_len;
        /// <summary>
        ///  Called from a core thread when there is something new to draw or
        ///  poll; `NULL` for none. See `tt_wakeup_fn`.
        /// </summary>
        public delegate* unmanaged[Cdecl]<void*, void> wakeup;
        /// <summary>
        ///  Passed to `wakeup` as is.
        /// </summary>
        public void* userdata;
    }

    /// <summary>
    ///  One terminal. Opaque to the host.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_term
    {
    }

    /// <summary>
    ///  UTF-8 text the host owns: `len` bytes at `ptr`, no terminator. `ptr`
    ///  may be `NULL` when `len` is 0.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_str
    {
        /// <summary>
        ///  The first byte.
        /// </summary>
        public byte* ptr;
        /// <summary>
        ///  Bytes, not characters.
        /// </summary>
        public nuint len;
    }

    /// <summary>
    ///  One event. A `u32` kind rather than an enum, so a kind added later is a
    ///  value an older host skips, not undefined behaviour.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_event
    {
        /// <summary>
        ///  `sizeof(tt_event)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  One of `TT_EVENT_*`; skip kinds you do not know.
        /// </summary>
        public uint kind;
        /// <summary>
        ///  `TT_EVENT_CHILD_EXITED`: the exit code, or `TT_EXIT_CODE_UNKNOWN`.
        /// </summary>
        public uint exit_code;
        /// <summary>
        ///  `TT_EVENT_CHILD_EXITED`: 1 when a signal ended the child.
        /// </summary>
        public byte signaled;
    }

    /// <summary>
    ///  One cell: 8 bytes, row after row, `cols * rows` of them.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_cell
    {
        /// <summary>
        ///  The first code point of the cell's text; 0 when it shows none.
        /// </summary>
        public uint codepoint;
        /// <summary>
        ///  Index into `tt_frame_view.styles`.
        /// </summary>
        public ushort style;
        /// <summary>
        ///  Columns covered: 1, 2 for a wide character, 0 for the cell behind it.
        /// </summary>
        public byte width;
        /// <summary>
        ///  `TT_CELL_CLUSTER` or 0.
        /// </summary>
        public byte flags;
    }

    /// <summary>
    ///  Neighbouring cells of one style and width with their text, the unit the
    ///  platform shaper takes. Blank cells belong to no run.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_run
    {
        /// <summary>
        ///  First column.
        /// </summary>
        public ushort col;
        /// <summary>
        ///  Columns covered, wide spacers included.
        /// </summary>
        public ushort cols;
        /// <summary>
        ///  Index into `tt_frame_view.styles`.
        /// </summary>
        public ushort style;
        /// <summary>
        ///  Columns per character: 1 or 2.
        /// </summary>
        public byte width;
        /// <summary>
        ///  Byte offset of the run's text in its row's `text`.
        /// </summary>
        public uint text_start;
        /// <summary>
        ///  Byte length of the run's text.
        /// </summary>
        public uint text_len;
    }

    /// <summary>
    ///  One viewport row: the line it shows and its text.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_row
    {
        /// <summary>
        ///  The line shown; stays with the line as it scrolls, so it keys a
        ///  cache of shaped rows.
        /// </summary>
        public ulong id;
        /// <summary>
        ///  Bumped by every change to the line.
        /// </summary>
        public uint generation;
        /// <summary>
        ///  The row's text runs, left to right.
        /// </summary>
        public tt_run* runs;
        /// <summary>
        ///  Number of runs.
        /// </summary>
        public nuint runs_len;
        /// <summary>
        ///  UTF-8 text of all runs, not NUL-terminated.
        /// </summary>
        public byte* text;
        /// <summary>
        ///  Bytes of text.
        /// </summary>
        public nuint text_len;
    }

    /// <summary>
    ///  A style as SGR set it; palette and reverse video are not resolved yet.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_style
    {
        /// <summary>
        ///  Foreground colour.
        /// </summary>
        public uint fg;
        /// <summary>
        ///  Background colour.
        /// </summary>
        public uint bg;
        /// <summary>
        ///  Underline colour; `TT_COLOR_DEFAULT` follows the foreground.
        /// </summary>
        public uint underline_color;
        /// <summary>
        ///  `TT_ATTR_*` bits.
        /// </summary>
        public ushort attrs;
        /// <summary>
        ///  A `TT_UNDERLINE_*` value.
        /// </summary>
        public byte underline;
    }

    /// <summary>
    ///  Rows `start..end` are, unchanged, the rows from `from` of the previous
    ///  picture: blit them before repainting the dirty rows.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_scroll
    {
        /// <summary>
        ///  First row moved into.
        /// </summary>
        public ushort start;
        /// <summary>
        ///  One past the last row moved into.
        /// </summary>
        public ushort end;
        /// <summary>
        ///  Where `start` was in the previous picture.
        /// </summary>
        public ushort from;
    }

    /// <summary>
    ///  The cursor in viewport rows.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_cursor
    {
        /// <summary>
        ///  Viewport row.
        /// </summary>
        public ushort row;
        /// <summary>
        ///  Column.
        /// </summary>
        public ushort col;
        /// <summary>
        ///  0 when hidden or scrolled out of the viewport.
        /// </summary>
        public byte visible;
    }

    /// <summary>
    ///  Where the frame shows the input method's composing text, set with
    ///  `tt_frame_preedit`. The text is already in the row's cells and runs and
    ///  the cursor is at its caret; a renderer only marks the span, usually
    ///  with an underline. `cols` is 0 when none is shown.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_preedit
    {
        /// <summary>
        ///  Viewport row.
        /// </summary>
        public ushort row;
        /// <summary>
        ///  First column.
        /// </summary>
        public ushort col;
        /// <summary>
        ///  Columns covered.
        /// </summary>
        public ushort cols;
    }

    /// <summary>
    ///  An image's pixels, shared and immutable. Opaque to the host: read it
    ///  with `tt_image_pixels`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_image
    {
    }

    /// <summary>
    ///  One image in the viewport. Draw the source rectangle of `image` scaled
    ///  to `cols` x `rows` cells whose top-left cell is (`row`, `col`), moved by
    ///  the pixel offset. Placements come lowest `z` first; a negative `z`
    ///  draws below the text.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_placement
    {
        /// <summary>
        ///  The pixels; valid until the next update or free of the frame, or
        ///  until `tt_image_release` after a `tt_image_retain`.
        /// </summary>
        public tt_image* image;
        /// <summary>
        ///  Changes whenever the pixels behind `image` may have; a texture cache
        ///  keys on `image` and `generation`.
        /// </summary>
        public ulong generation;
        /// <summary>
        ///  Viewport row of the top-left cell; negative above the viewport.
        /// </summary>
        public int row;
        /// <summary>
        ///  Column of the top-left cell.
        /// </summary>
        public uint col;
        /// <summary>
        ///  Width in cells.
        /// </summary>
        public uint cols;
        /// <summary>
        ///  Height in cells.
        /// </summary>
        public uint rows;
        /// <summary>
        ///  Pixel offset inside the top-left cell.
        /// </summary>
        public uint offset_x;
        /// <summary>
        ///  Pixel offset inside the top-left cell.
        /// </summary>
        public uint offset_y;
        /// <summary>
        ///  Source rectangle in image pixels: left edge.
        /// </summary>
        public uint src_x;
        /// <summary>
        ///  Top edge.
        /// </summary>
        public uint src_y;
        /// <summary>
        ///  Width.
        /// </summary>
        public uint src_w;
        /// <summary>
        ///  Height.
        /// </summary>
        public uint src_h;
        /// <summary>
        ///  Stacking order.
        /// </summary>
        public int z;
    }

    /// <summary>
    ///  What `tt_frame_update` hands back. Set `struct_size` before the call.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_frame_view
    {
        /// <summary>
        ///  `sizeof(tt_frame_view)` as the host knows it; on return, the bytes
        ///  the core filled in.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  Columns.
        /// </summary>
        public ushort cols;
        /// <summary>
        ///  Rows.
        /// </summary>
        public ushort rows;
        /// <summary>
        ///  0 while synchronized output (mode 2026) holds the picture: nothing
        ///  changed and there is no damage; keep showing the last frame.
        /// </summary>
        public byte updated;
        /// <summary>
        ///  1 when every row must be repainted (first frame, resize, other
        ///  screen); every row is then also listed in `dirty`.
        /// </summary>
        public byte full;
        /// <summary>
        ///  The cursor.
        /// </summary>
        public tt_cursor cursor;
        /// <summary>
        ///  `cols * rows` cells, row-major.
        /// </summary>
        public tt_cell* cells;
        /// <summary>
        ///  Number of cells.
        /// </summary>
        public nuint cells_len;
        /// <summary>
        ///  One entry per viewport row.
        /// </summary>
        public tt_row* lines;
        /// <summary>
        ///  Number of rows in `lines`.
        /// </summary>
        public nuint lines_len;
        /// <summary>
        ///  The style table that cells and runs index; entry 0 is the default.
        /// </summary>
        public tt_style* styles;
        /// <summary>
        ///  Number of styles.
        /// </summary>
        public nuint styles_len;
        /// <summary>
        ///  Rows to blit from the previous picture, applied before `dirty`.
        /// </summary>
        public tt_scroll* scrolls;
        /// <summary>
        ///  Number of scrolls.
        /// </summary>
        public nuint scrolls_len;
        /// <summary>
        ///  Rows to repaint, top to bottom.
        /// </summary>
        public ushort* dirty;
        /// <summary>
        ///  Number of dirty rows.
        /// </summary>
        public nuint dirty_len;
        /// <summary>
        ///  The images in the viewport, lowest `z` first. The rows they cover
        ///  are in `dirty` whenever a placement over them changed.
        /// </summary>
        public tt_placement* placements;
        /// <summary>
        ///  Number of placements.
        /// </summary>
        public nuint placements_len;
        /// <summary>
        ///  The composing text's span; its row is in `dirty` whenever it
        ///  changed.
        /// </summary>
        public tt_preedit preedit;
    }

    /// <summary>
    ///  A UI-owned frame. Opaque to the host; one per view, used from one
    ///  thread at a time.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_frame
    {
    }

    /// <summary>
    ///  One key event, as Ghostty's embedding API reports it: what was
    ///  pressed and what text it typed; the core picks the bytes.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_key_event
    {
        /// <summary>
        ///  `sizeof(tt_key_event)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  The key: for a key of the main block, the code point it types on
        ///  the US layout with no modifiers (`'a'`, `'1'`, `' '`); for any
        ///  other key a `TT_KEY_*` code.
        /// </summary>
        public uint key;
        /// <summary>
        ///  What the key types on the current layout with no modifiers (`с`
        ///  for the `c` key on a Russian layout); 0 when it is `key` itself.
        /// </summary>
        public uint unshifted;
        /// <summary>
        ///  `TT_KEY_PRESS`, `TT_KEY_REPEAT` or `TT_KEY_RELEASE`.
        /// </summary>
        public byte action;
        /// <summary>
        ///  `TT_MOD_*` bits held, including this key if it is a modifier.
        /// </summary>
        public byte mods;
        /// <summary>
        ///  `TT_MOD_*` bits the layout used to type `text` (Option typing `å`).
        /// </summary>
        public byte consumed_mods;
        /// <summary>
        ///  1 while an input method is composing: nothing is sent.
        /// </summary>
        public byte composing;
        /// <summary>
        ///  UTF-8 the key typed, with Shift and consumed modifiers but not
        ///  Control applied; may be empty.
        /// </summary>
        public tt_str text;
    }

    /// <summary>
    ///  One mouse event, in cells and in pixels: the core picks which the
    ///  program gets.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_mouse_event
    {
        /// <summary>
        ///  `sizeof(tt_mouse_event)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  `TT_MOUSE_PRESS`, `TT_MOUSE_RELEASE` or `TT_MOUSE_MOTION`.
        /// </summary>
        public byte action;
        /// <summary>
        ///  The button pressed or released; for motion, the lowest one held or
        ///  `TT_MOUSE_NONE`.
        /// </summary>
        public byte button;
        /// <summary>
        ///  `TT_MOD_*` bits; Shift, Alt and Control are reported.
        /// </summary>
        public byte mods;
        /// <summary>
        ///  Viewport column, from 0.
        /// </summary>
        public uint col;
        /// <summary>
        ///  Viewport row, from 0.
        /// </summary>
        public uint row;
        /// <summary>
        ///  Pixels from the left of the text area.
        /// </summary>
        public uint x_px;
        /// <summary>
        ///  Pixels from the top of the text area.
        /// </summary>
        public uint y_px;
    }


    /// <summary>
    ///  What every fallible call answers. Values are only ever appended.
    /// </summary>
    internal enum tt_status : int
    {
        /// <summary>
        ///  Done.
        /// </summary>
        TT_OK = 0,
        /// <summary>
        ///  A `NULL` handle or pointer, a `struct_size` too small, a size of
        ///  zero, or text that is not UTF-8.
        /// </summary>
        TT_INVALID = 1,
        /// <summary>
        ///  The host was built against another ABI version.
        /// </summary>
        TT_ABI_MISMATCH = 2,
        /// <summary>
        ///  An earlier call panicked inside this terminal; only
        ///  `tt_term_free` is left to call.
        /// </summary>
        TT_POISONED = 3,
        /// <summary>
        ///  This call panicked inside the core; the terminal is now poisoned.
        /// </summary>
        TT_PANIC = 4,
        /// <summary>
        ///  Nothing to report: the event queue is empty.
        /// </summary>
        TT_EMPTY = 5,
        /// <summary>
        ///  The terminal has no child to talk to: it was made by
        ///  `tt_term_new`, or its child has gone.
        /// </summary>
        TT_CLOSED = 6,
        /// <summary>
        ///  The operating system refused: no PTY, a program that does not
        ///  start, a size the PTY rejects.
        /// </summary>
        TT_IO = 7,
        /// <summary>
        ///  The child is not reading and its input queue cannot take the whole
        ///  event; nothing was sent. Try again later.
        /// </summary>
        TT_FULL = 8,
    }


}
