// Copyright (c) 2026 Ivan Tugay
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by csbindgen from crates/scull-ffi/src: `just bindings`. Do not edit.
// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Scull.Native
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "scull_ffi";

        /// <summary>
        ///  Breaking changes bump the major version; a host refuses to run on
        ///  another major.
        /// </summary>
        internal const uint TT_ABI_VERSION_MAJOR = 0;
        /// <summary>
        ///  Additions (new functions, fields appended to a struct) bump the minor.
        ///  While the major is 0 every minor may break, so the minor must match too.
        /// </summary>
        internal const uint TT_ABI_VERSION_MINOR = 1;
        /// <summary>
        ///  The version a host was built against, `major &lt;&lt; 16 | minor`; pass it
        ///  in `tt_term_options.abi_version`.
        /// </summary>
        internal const uint TT_ABI_VERSION = 1;
        /// <summary>
        ///  `tt_event.kind`: the program rang the bell, once or more since the last
        ///  poll.
        /// </summary>
        internal const uint TT_EVENT_BELL = 1;
        /// <summary>
        ///  `tt_event.kind`: the child ended and all its output has been parsed.
        ///  Reported once, last.
        /// </summary>
        internal const uint TT_EVENT_CHILD_EXITED = 2;
        /// <summary>
        ///  `tt_event.exit_code` when the system did not say. A literal, not the
        ///  PTY crate's constant, so the generated header can spell it.
        /// </summary>
        internal const uint TT_EXIT_CODE_UNKNOWN = 4294967295;
        /// <summary>
        ///  The cell holds more code points than `codepoint`; the whole cluster is
        ///  in its row's text.
        /// </summary>
        internal const byte TT_CELL_CLUSTER = 1;
        /// <summary>
        ///  A colour: `TT_COLOR_DEFAULT`, `TT_COLOR_INDEXED | index` or
        ///  `TT_COLOR_RGB | 0xRRGGBB`; the kind is in `TT_COLOR_KIND_MASK`.
        /// </summary>
        internal const uint TT_COLOR_DEFAULT = 0;
        /// <summary>
        ///  Palette colour, index in the low byte.
        /// </summary>
        internal const uint TT_COLOR_INDEXED = 16777216;
        /// <summary>
        ///  True colour in the low three bytes.
        /// </summary>
        internal const uint TT_COLOR_RGB = 33554432;
        /// <summary>
        ///  The bits that hold a colour's kind.
        /// </summary>
        internal const uint TT_COLOR_KIND_MASK = 4278190080;
        /// <summary>
        ///  `tt_style.attrs` bits.
        /// </summary>
        internal const ushort TT_ATTR_BOLD = 1;
        /// <summary>
        ///  Faint.
        /// </summary>
        internal const ushort TT_ATTR_DIM = 2;
        /// <summary>
        ///  Italic.
        /// </summary>
        internal const ushort TT_ATTR_ITALIC = 4;
        /// <summary>
        ///  Blinking.
        /// </summary>
        internal const ushort TT_ATTR_BLINK = 8;
        /// <summary>
        ///  Foreground and background swapped.
        /// </summary>
        internal const ushort TT_ATTR_INVERSE = 16;
        /// <summary>
        ///  Invisible text.
        /// </summary>
        internal const ushort TT_ATTR_HIDDEN = 32;
        /// <summary>
        ///  Struck through.
        /// </summary>
        internal const ushort TT_ATTR_STRIKE = 64;
        /// <summary>
        ///  Line above.
        /// </summary>
        internal const ushort TT_ATTR_OVERLINE = 128;
        /// <summary>
        ///  `tt_style.underline` values.
        /// </summary>
        internal const byte TT_UNDERLINE_NONE = 0;
        /// <summary>
        ///  One line.
        /// </summary>
        internal const byte TT_UNDERLINE_SINGLE = 1;
        /// <summary>
        ///  Two lines.
        /// </summary>
        internal const byte TT_UNDERLINE_DOUBLE = 2;
        /// <summary>
        ///  Wavy.
        /// </summary>
        internal const byte TT_UNDERLINE_CURLY = 3;
        /// <summary>
        ///  Dotted.
        /// </summary>
        internal const byte TT_UNDERLINE_DOTTED = 4;
        /// <summary>
        ///  Dashed.
        /// </summary>
        internal const byte TT_UNDERLINE_DASHED = 5;




        /// <summary>
        ///  The ABI version of this library, `major &lt;&lt; 16 | minor`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_abi_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern uint tt_abi_version();

        /// <summary>
        ///  Creates a terminal with no child process: bytes reach it only through
        ///  `tt_term_feed`. On `TT_OK` `*out` holds the handle; free it with
        ///  `tt_term_free`.
        ///
        ///  # Safety
        ///
        ///  `options` is `NULL` or points to `struct_size` readable bytes; `out` is
        ///  `NULL` or writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_new(tt_term_options* options, tt_term** @out);

        /// <summary>
        ///  Parses `len` bytes of program output into the terminal, as if the
        ///  child had written them. `bytes` may be `NULL` when `len` is 0.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `bytes` points to `len` readable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_feed", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_feed(tt_term* term, byte* bytes, nuint len);

        /// <summary>
        ///  Resizes the terminal to `cols` x `rows` cells: the primary screen and
        ///  its history are rewrapped, the alternate screen is cut or padded. The
        ///  child, if any, is told the new size (`width_px` and `height_px` are the
        ///  view's size in pixels, 0 if unknown) and output paused by
        ///  `tt_term_resize_begin` flows again, whatever the outcome.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_resize", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_resize(tt_term* term, ushort cols, ushort rows, ushort width_px, ushort height_px);

        /// <summary>
        ///  Frees the terminal. Also valid on a poisoned terminal; `NULL` is a
        ///  no-op. No other call may use `term` during or after this one.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live, and not used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_term_free(tt_term* term);

        /// <summary>
        ///  Creates a terminal running a child on a new PTY: `options.program`
        ///  with its arguments, or the user's shell. Output is parsed on core
        ///  threads; `options.wakeup` says when to look. On `TT_OK` `*out` holds
        ///  the handle; free it with `tt_term_free`, which ends the child.
        ///
        ///  # Safety
        ///
        ///  As for `tt_term_new`; the strings and arrays in `*options` are valid
        ///  for their lengths, during this call only.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_spawn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_spawn(tt_term_options* options, tt_term** @out);

        /// <summary>
        ///  Queues `len` bytes of input (keys, paste) for the child without
        ///  blocking. `*written` gets how many leading bytes were taken: fewer than
        ///  `len` when the child is not reading; offer the rest later. `TT_CLOSED`
        ///  when there is no child or it has gone.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `bytes` points to `len` readable bytes;
        ///  `written` is `NULL` or writable.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_write", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_write(tt_term* term, byte* bytes, nuint len, nuint* written);

        /// <summary>
        ///  Starts an interactive resize: the child's output is held back, so the
        ///  host keeps drawing the last frame, until `tt_term_resize` with the final
        ///  size. Without it every intermediate size would rewrap the history.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_resize_begin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_resize_begin(tt_term* term);

        /// <summary>
        ///  Takes the next event into `*event`: `TT_OK` with one, `TT_EMPTY` when
        ///  there is none. Call it until `TT_EMPTY` after every wakeup.
        ///
        ///  # Safety
        ///
        ///  `term` is `NULL` or live; `event` is `NULL` or points to `struct_size`
        ///  writable bytes.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_term_poll_event", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_term_poll_event(tt_term* term, tt_event* @event);

        /// <summary>
        ///  A new, empty frame; the first update fills it. `NULL` only if the core
        ///  failed. Free it with `tt_frame_free`.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_new", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_frame* tt_frame_new();

        /// <summary>
        ///  Brings `frame` up to date with `term`'s viewport and describes it in
        ///  `*view`. Holds the terminal lock only while it copies the rows that
        ///  changed. The pointers in `*view` stay valid until the next update or
        ///  free of this frame.
        ///
        ///  # Safety
        ///
        ///  `frame` and `term` are `NULL` or live; `view` is `NULL` or points to
        ///  `struct_size` writable bytes. No other thread uses `frame` meanwhile.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_update", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern tt_status tt_frame_update(tt_frame* frame, tt_term* term, tt_frame_view* view);

        /// <summary>
        ///  Frees the frame and every buffer its views pointed to. `NULL` is a
        ///  no-op.
        ///
        ///  # Safety
        ///
        ///  `frame` is `NULL` or live, and not used again.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tt_frame_free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tt_frame_free(tt_frame* frame);


    }

    /// <summary>
    ///  How to create a terminal. Fields a host does not know read as zero;
    ///  `tt_term_new` reads only up to `scrollback`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_term_options
    {
        /// <summary>
        ///  `sizeof(tt_term_options)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  `TT_ABI_VERSION` as the host was built with it.
        /// </summary>
        public uint abi_version;
        /// <summary>
        ///  Columns, at least 1.
        /// </summary>
        public ushort cols;
        /// <summary>
        ///  Rows, at least 1.
        /// </summary>
        public ushort rows;
        /// <summary>
        ///  History rows to keep; the core clamps it.
        /// </summary>
        public uint scrollback;
        /// <summary>
        ///  The program, searched on `PATH`; empty runs the user's shell.
        /// </summary>
        public tt_str program;
        /// <summary>
        ///  `args_len` arguments; ignored for the user's shell.
        /// </summary>
        public tt_str* args;
        /// <summary>
        ///  Number of `args`.
        /// </summary>
        public nuint args_len;
        /// <summary>
        ///  Working directory; empty keeps the host's.
        /// </summary>
        public tt_str cwd;
        /// <summary>
        ///  `env_len` `NAME=value` entries added to the host's environment.
        /// </summary>
        public tt_str* env;
        /// <summary>
        ///  Number of `env`.
        /// </summary>
        public nuint env_len;
        /// <summary>
        ///  Called from a core thread when there is something new to draw or
        ///  poll; `NULL` for none. See `tt_wakeup_fn`.
        /// </summary>
        public delegate* unmanaged[Cdecl]<void*, void> wakeup;
        /// <summary>
        ///  Passed to `wakeup` as is.
        /// </summary>
        public void* userdata;
    }

    /// <summary>
    ///  One terminal. Opaque to the host.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_term
    {
    }

    /// <summary>
    ///  UTF-8 text the host owns: `len` bytes at `ptr`, no terminator. `ptr`
    ///  may be `NULL` when `len` is 0.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_str
    {
        /// <summary>
        ///  The first byte.
        /// </summary>
        public byte* ptr;
        /// <summary>
        ///  Bytes, not characters.
        /// </summary>
        public nuint len;
    }

    /// <summary>
    ///  One event. A `u32` kind rather than an enum, so a kind added later is a
    ///  value an older host skips, not undefined behaviour.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_event
    {
        /// <summary>
        ///  `sizeof(tt_event)` as the host knows it.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  One of `TT_EVENT_*`; skip kinds you do not know.
        /// </summary>
        public uint kind;
        /// <summary>
        ///  `TT_EVENT_CHILD_EXITED`: the exit code, or `TT_EXIT_CODE_UNKNOWN`.
        /// </summary>
        public uint exit_code;
        /// <summary>
        ///  `TT_EVENT_CHILD_EXITED`: 1 when a signal ended the child.
        /// </summary>
        public byte signaled;
    }

    /// <summary>
    ///  One cell: 8 bytes, row after row, `cols * rows` of them.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_cell
    {
        /// <summary>
        ///  The first code point of the cell's text; 0 when it shows none.
        /// </summary>
        public uint codepoint;
        /// <summary>
        ///  Index into `tt_frame_view.styles`.
        /// </summary>
        public ushort style;
        /// <summary>
        ///  Columns covered: 1, 2 for a wide character, 0 for the cell behind it.
        /// </summary>
        public byte width;
        /// <summary>
        ///  `TT_CELL_CLUSTER` or 0.
        /// </summary>
        public byte flags;
    }

    /// <summary>
    ///  Neighbouring cells of one style and width with their text, the unit the
    ///  platform shaper takes. Blank cells belong to no run.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_run
    {
        /// <summary>
        ///  First column.
        /// </summary>
        public ushort col;
        /// <summary>
        ///  Columns covered, wide spacers included.
        /// </summary>
        public ushort cols;
        /// <summary>
        ///  Index into `tt_frame_view.styles`.
        /// </summary>
        public ushort style;
        /// <summary>
        ///  Columns per character: 1 or 2.
        /// </summary>
        public byte width;
        /// <summary>
        ///  Byte offset of the run's text in its row's `text`.
        /// </summary>
        public uint text_start;
        /// <summary>
        ///  Byte length of the run's text.
        /// </summary>
        public uint text_len;
    }

    /// <summary>
    ///  One viewport row: the line it shows and its text.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_row
    {
        /// <summary>
        ///  The line shown; stays with the line as it scrolls, so it keys a
        ///  cache of shaped rows.
        /// </summary>
        public ulong id;
        /// <summary>
        ///  Bumped by every change to the line.
        /// </summary>
        public uint generation;
        /// <summary>
        ///  The row's text runs, left to right.
        /// </summary>
        public tt_run* runs;
        /// <summary>
        ///  Number of runs.
        /// </summary>
        public nuint runs_len;
        /// <summary>
        ///  UTF-8 text of all runs, not NUL-terminated.
        /// </summary>
        public byte* text;
        /// <summary>
        ///  Bytes of text.
        /// </summary>
        public nuint text_len;
    }

    /// <summary>
    ///  A style as SGR set it; palette and reverse video are not resolved yet.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_style
    {
        /// <summary>
        ///  Foreground colour.
        /// </summary>
        public uint fg;
        /// <summary>
        ///  Background colour.
        /// </summary>
        public uint bg;
        /// <summary>
        ///  Underline colour; `TT_COLOR_DEFAULT` follows the foreground.
        /// </summary>
        public uint underline_color;
        /// <summary>
        ///  `TT_ATTR_*` bits.
        /// </summary>
        public ushort attrs;
        /// <summary>
        ///  A `TT_UNDERLINE_*` value.
        /// </summary>
        public byte underline;
    }

    /// <summary>
    ///  Rows `start..end` are, unchanged, the rows from `from` of the previous
    ///  picture: blit them before repainting the dirty rows.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_scroll
    {
        /// <summary>
        ///  First row moved into.
        /// </summary>
        public ushort start;
        /// <summary>
        ///  One past the last row moved into.
        /// </summary>
        public ushort end;
        /// <summary>
        ///  Where `start` was in the previous picture.
        /// </summary>
        public ushort from;
    }

    /// <summary>
    ///  The cursor in viewport rows.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_cursor
    {
        /// <summary>
        ///  Viewport row.
        /// </summary>
        public ushort row;
        /// <summary>
        ///  Column.
        /// </summary>
        public ushort col;
        /// <summary>
        ///  0 when hidden or scrolled out of the viewport.
        /// </summary>
        public byte visible;
    }

    /// <summary>
    ///  What `tt_frame_update` hands back. Set `struct_size` before the call.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_frame_view
    {
        /// <summary>
        ///  `sizeof(tt_frame_view)` as the host knows it; on return, the bytes
        ///  the core filled in.
        /// </summary>
        public uint struct_size;
        /// <summary>
        ///  Columns.
        /// </summary>
        public ushort cols;
        /// <summary>
        ///  Rows.
        /// </summary>
        public ushort rows;
        /// <summary>
        ///  0 while synchronized output (mode 2026) holds the picture: nothing
        ///  changed and there is no damage; keep showing the last frame.
        /// </summary>
        public byte updated;
        /// <summary>
        ///  1 when every row must be repainted (first frame, resize, other
        ///  screen); every row is then also listed in `dirty`.
        /// </summary>
        public byte full;
        /// <summary>
        ///  The cursor.
        /// </summary>
        public tt_cursor cursor;
        /// <summary>
        ///  `cols * rows` cells, row-major.
        /// </summary>
        public tt_cell* cells;
        /// <summary>
        ///  Number of cells.
        /// </summary>
        public nuint cells_len;
        /// <summary>
        ///  One entry per viewport row.
        /// </summary>
        public tt_row* lines;
        /// <summary>
        ///  Number of rows in `lines`.
        /// </summary>
        public nuint lines_len;
        /// <summary>
        ///  The style table that cells and runs index; entry 0 is the default.
        /// </summary>
        public tt_style* styles;
        /// <summary>
        ///  Number of styles.
        /// </summary>
        public nuint styles_len;
        /// <summary>
        ///  Rows to blit from the previous picture, applied before `dirty`.
        /// </summary>
        public tt_scroll* scrolls;
        /// <summary>
        ///  Number of scrolls.
        /// </summary>
        public nuint scrolls_len;
        /// <summary>
        ///  Rows to repaint, top to bottom.
        /// </summary>
        public ushort* dirty;
        /// <summary>
        ///  Number of dirty rows.
        /// </summary>
        public nuint dirty_len;
    }

    /// <summary>
    ///  A UI-owned frame. Opaque to the host; one per view, used from one
    ///  thread at a time.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct tt_frame
    {
    }


    /// <summary>
    ///  What every fallible call answers. Values are only ever appended.
    /// </summary>
    internal enum tt_status : int
    {
        /// <summary>
        ///  Done.
        /// </summary>
        TT_OK = 0,
        /// <summary>
        ///  A `NULL` handle or pointer, a `struct_size` too small, a size of
        ///  zero, or text that is not UTF-8.
        /// </summary>
        TT_INVALID = 1,
        /// <summary>
        ///  The host was built against another ABI version.
        /// </summary>
        TT_ABI_MISMATCH = 2,
        /// <summary>
        ///  An earlier call panicked inside this terminal; only
        ///  `tt_term_free` is left to call.
        /// </summary>
        TT_POISONED = 3,
        /// <summary>
        ///  This call panicked inside the core; the terminal is now poisoned.
        /// </summary>
        TT_PANIC = 4,
        /// <summary>
        ///  Nothing to report: the event queue is empty.
        /// </summary>
        TT_EMPTY = 5,
        /// <summary>
        ///  The terminal has no child to talk to: it was made by
        ///  `tt_term_new`, or its child has gone.
        /// </summary>
        TT_CLOSED = 6,
        /// <summary>
        ///  The operating system refused: no PTY, a program that does not
        ///  start, a size the PTY rejects.
        /// </summary>
        TT_IO = 7,
    }


}
